In [1]:
# %pylab
import pandas as pd
import csv
import numpy as np
import matplotlib.pyplot as plt
# pd.set_option('display.mpl_style', 'default') 
# pd.set_option('display.line_width', 5000) 
# pd.set_option('display.max_columns', 60) 

# figsize(15, 5)

In [2]:
num_students_thresh = 0

# Reading Scores

In [3]:
# fields = ['NCESSCH', 'ALL_RLA00PCTPROF_1314']

# data_reading = pd.read_csv('reading.csv', error_bad_lines=False, quoting=csv.QUOTE_NONE)
# data_reading = pd.read_csv('reading_adjusted.csv', error_bad_lines=False, quoting=csv.QUOTE_NONE)
data_reading = pd.read_csv('data/reading_adjust.csv', error_bad_lines=False, quoting=csv.QUOTE_NONE, encoding='utf-8')

data_reading.shape

(82378, 3)

In [4]:
data_reading

            NCESSCH  ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
0       10000500870                     628                    29
1       10000500871                     301                    60
2       10000500879                     664                    32
3       10000500889                     787                    30
4       10000600193                     442                    41
5       10000600872                     282                    35
6       10000600876                      39                 30-39
7       10000600877                     479                    28
8       10000600878                     157                 50-54
9       10000600880                     244                    32
10      10000600883                     119                 65-69
11      10000601434                     242                    37
12      10000601585                     105                 55-59
13      10000601685                     169                 40-44
14      10000601812                     447                    39
15      10000602209                     267                    15
16      10000700091                     192                 45-49
17      10000700248                     299                    60
18      10000700251                     664                    79
19      10000700337                    1171                    66
20      10000700342                     228                    48
21      10000701422                     854                    58
22      10000701456                     401                    80
23      10000701483                     354                    51
24      10000701738                     303                    57
25      10000701739                     214                    40
26      10000701740                     279                    45
27      10000701741                     844                    60
28      10000701742                     274                    48
29      10000701743                     165                 50-54
...             ...                     ...                   ...
82348  560570000323                      20                 21-39
82349  560570000362                     105                 50-54
82350  560570000510                      53                 30-39
82351  560576200164                      12                  LT50
82352  560576200285                     366                    39
82353  560576200324                     159                 20-24
82354  560576200326                       2                    PS
82355  560576200329                       1                    PS
82356  560576200332                      62                 55-59
82357  560576200399                     383                    53
82358  560576200424                      78                 55-59
82359  560576200425                      99                 40-44
82360  560576200439                      81                 60-64
82361  560582000393                      36                 40-49
82362  560583000289                     332                    46
82363  560583000335                     114                 25-29
82364  560583000336                     408                    56
82365  560583000337                      10                  GE50
82366  560583000339                      13                  GE50
82367  560583000340                       3                    PS
82368  560583000341                      62                 65-69
82369  560583000512                      21                  LE20
82370  560609000342                      54                 50-59
82371  560609000363                      49                 50-59
82372  560609000401                      18                 21-39
82373  560624000343                      62                 30-34
82374  560624000344                     266                    52
82375  560624000345                      93                 50-54
82376  560624000346                      70                 65-69
82377  560624000347                      84                 50-54

[82378 rows x 3 columns]

In [5]:
data_reading['ALL_RLA00PCTPROF_1314'][82354]

'PS'

In [6]:
data_reading.shape

(82378, 3)

In [7]:
data_reading = data_reading[data_reading['ALL_RLA00PCTPROF_1314'] != 'PS']

In [8]:
data_reading.shape

(78377, 3)

In [9]:
data_reading

            NCESSCH  ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
0       10000500870                     628                    29
1       10000500871                     301                    60
2       10000500879                     664                    32
3       10000500889                     787                    30
4       10000600193                     442                    41
5       10000600872                     282                    35
6       10000600876                      39                 30-39
7       10000600877                     479                    28
8       10000600878                     157                 50-54
9       10000600880                     244                    32
10      10000600883                     119                 65-69
11      10000601434                     242                    37
12      10000601585                     105                 55-59
13      10000601685                     169                 40-44
14      10000601812                     447                    39
15      10000602209                     267                    15
16      10000700091                     192                 45-49
17      10000700248                     299                    60
18      10000700251                     664                    79
19      10000700337                    1171                    66
20      10000700342                     228                    48
21      10000701422                     854                    58
22      10000701456                     401                    80
23      10000701483                     354                    51
24      10000701738                     303                    57
25      10000701739                     214                    40
26      10000701740                     279                    45
27      10000701741                     844                    60
28      10000701742                     274                    48
29      10000701743                     165                 50-54
...             ...                     ...                   ...
82345  560569500361                     472                    67
82346  560569500397                     122                 75-79
82347  560569500474                     119                 70-74
82348  560570000323                      20                 21-39
82349  560570000362                     105                 50-54
82350  560570000510                      53                 30-39
82351  560576200164                      12                  LT50
82352  560576200285                     366                    39
82353  560576200324                     159                 20-24
82356  560576200332                      62                 55-59
82357  560576200399                     383                    53
82358  560576200424                      78                 55-59
82359  560576200425                      99                 40-44
82360  560576200439                      81                 60-64
82361  560582000393                      36                 40-49
82362  560583000289                     332                    46
82363  560583000335                     114                 25-29
82364  560583000336                     408                    56
82365  560583000337                      10                  GE50
82366  560583000339                      13                  GE50
82368  560583000341                      62                 65-69
82369  560583000512                      21                  LE20
82370  560609000342                      54                 50-59
82371  560609000363                      49                 50-59
82372  560609000401                      18                 21-39
82373  560624000343                      62                 30-34
82374  560624000344                     266                    52
82375  560624000345                      93                 50-54
82376  560624000346                      70                 65-69
82377  560624000347                      84                 50-54

[78377 rows x 3 columns]

In [10]:
data_reading['NCESSCH'].dtype

dtype('int64')

In [11]:
data_reading[['ALL_RLA00NUMVALID_1314' ,'ALL_RLA00PCTPROF_1314']][78365:-1]

       ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
82365                      10                  GE50
82366                      13                  GE50
82368                      62                 65-69
82369                      21                  LE20
82370                      54                 50-59
82371                      49                 50-59
82372                      18                 21-39
82373                      62                 30-34
82374                     266                    52
82375                      93                 50-54
82376                      70                 65-69

In [12]:
data_reading0 = data_reading.copy()

lt_rows = data_reading0['ALL_RLA00PCTPROF_1314'].str.contains('LT')
le_rows = data_reading0['ALL_RLA00PCTPROF_1314'].str.contains('LE')
ge_rows = data_reading0['ALL_RLA00PCTPROF_1314'].str.contains('GE')

data_reading0.replace({'ALL_RLA00PCTPROF_1314': {r'^(LE|GE|LT*)': ''}}, regex=True, inplace=True)

In [13]:
data_reading0[['ALL_RLA00NUMVALID_1314' ,'ALL_RLA00PCTPROF_1314']][78365:-1]

       ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
82365                      10                    50
82366                      13                    50
82368                      62                 65-69
82369                      21                    20
82370                      54                 50-59
82371                      49                 50-59
82372                      18                 21-39
82373                      62                 30-34
82374                     266                    52
82375                      93                 50-54
82376                      70                 65-69

In [14]:
data_reading2 = data_reading0.copy()

data_reading2.loc[lt_rows, ('ALL_RLA00PCTPROF_1314')] = data_reading0['ALL_RLA00PCTPROF_1314'][lt_rows].astype(float) / 2
data_reading2.loc[le_rows, ('ALL_RLA00PCTPROF_1314')] = data_reading0['ALL_RLA00PCTPROF_1314'][le_rows].astype(float) / 2
data_reading2.loc[ge_rows, ('ALL_RLA00PCTPROF_1314')] = (data_reading0['ALL_RLA00PCTPROF_1314'][ge_rows].astype(float) + 100) / 2

In [15]:
data_reading2[['ALL_RLA00NUMVALID_1314' ,'ALL_RLA00PCTPROF_1314']][78365:-1]

       ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
82365                      10                    75
82366                      13                    75
82368                      62                 65-69
82369                      21                    10
82370                      54                 50-59
82371                      49                 50-59
82372                      18                 21-39
82373                      62                 30-34
82374                     266                    52
82375                      93                 50-54
82376                      70                 65-69

In [16]:
data_reading2.shape

(78377, 3)

In [17]:
data_reading2[['ALL_RLA00NUMVALID_1314' ,'ALL_RLA00PCTPROF_1314']][78365:-1]

       ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
82365                      10                    75
82366                      13                    75
82368                      62                 65-69
82369                      21                    10
82370                      54                 50-59
82371                      49                 50-59
82372                      18                 21-39
82373                      62                 30-34
82374                     266                    52
82375                      93                 50-54
82376                      70                 65-69

In [18]:
# df = data_reading.copy()
# data_reading.replace({'ALL_RLA00PCTPROF_1314': {r'^(LE|GE|LT*)': '', '(-.*)': ''}}, regex=True, inplace=True)

data_reading3 = data_reading2.copy()

a = data_reading2['ALL_RLA00PCTPROF_1314'].astype(str).str.contains('-')

data_reading3.loc[a, ('ALL_RLA00PCTPROF_1314')] = data_reading2['ALL_RLA00PCTPROF_1314'][a].str.split('-', expand=True).astype(float).mean(axis=1)

In [19]:
data_reading3[['ALL_RLA00NUMVALID_1314' ,'ALL_RLA00PCTPROF_1314']][78365:-1]

       ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
82365                      10                    75
82366                      13                    75
82368                      62                    67
82369                      21                    10
82370                      54                  54.5
82371                      49                  54.5
82372                      18                    30
82373                      62                    32
82374                     266                    52
82375                      93                    52
82376                      70                    67

In [20]:
low_students = data_reading3['ALL_RLA00NUMVALID_1314'] > num_students_thresh

data_reading3 = data_reading3[low_students]

In [21]:
data_reading3.shape

(78377, 3)

In [22]:
data_reading3[['ALL_RLA00NUMVALID_1314' ,'ALL_RLA00PCTPROF_1314']][78365:-1]

       ALL_RLA00NUMVALID_1314 ALL_RLA00PCTPROF_1314
82365                      10                    75
82366                      13                    75
82368                      62                    67
82369                      21                    10
82370                      54                  54.5
82371                      49                  54.5
82372                      18                    30
82373                      62                    32
82374                     266                    52
82375                      93                    52
82376                      70                    67

In [23]:
data_reading3.to_csv('data/final_data/reading_final.csv',index=False, encoding='utf-8')

In [24]:
data_test_reading = pd.read_csv('data/final_data/reading_final.csv')
data_test_reading

            NCESSCH  ALL_RLA00NUMVALID_1314  ALL_RLA00PCTPROF_1314
0       10000500870                     628                   29.0
1       10000500871                     301                   60.0
2       10000500879                     664                   32.0
3       10000500889                     787                   30.0
4       10000600193                     442                   41.0
5       10000600872                     282                   35.0
6       10000600876                      39                   34.5
7       10000600877                     479                   28.0
8       10000600878                     157                   52.0
9       10000600880                     244                   32.0
10      10000600883                     119                   67.0
11      10000601434                     242                   37.0
12      10000601585                     105                   57.0
13      10000601685                     169                   42.0
14      10000601812                     447                   39.0
15      10000602209                     267                   15.0
16      10000700091                     192                   47.0
17      10000700248                     299                   60.0
18      10000700251                     664                   79.0
19      10000700337                    1171                   66.0
20      10000700342                     228                   48.0
21      10000701422                     854                   58.0
22      10000701456                     401                   80.0
23      10000701483                     354                   51.0
24      10000701738                     303                   57.0
25      10000701739                     214                   40.0
26      10000701740                     279                   45.0
27      10000701741                     844                   60.0
28      10000701742                     274                   48.0
29      10000701743                     165                   52.0
...             ...                     ...                    ...
78347  560569500361                     472                   67.0
78348  560569500397                     122                   77.0
78349  560569500474                     119                   72.0
78350  560570000323                      20                   30.0
78351  560570000362                     105                   52.0
78352  560570000510                      53                   34.5
78353  560576200164                      12                   25.0
78354  560576200285                     366                   39.0
78355  560576200324                     159                   22.0
78356  560576200332                      62                   57.0
78357  560576200399                     383                   53.0
78358  560576200424                      78                   57.0
78359  560576200425                      99                   42.0
78360  560576200439                      81                   62.0
78361  560582000393                      36                   44.5
78362  560583000289                     332                   46.0
78363  560583000335                     114                   27.0
78364  560583000336                     408                   56.0
78365  560583000337                      10                   75.0
78366  560583000339                      13                   75.0
78367  560583000341                      62                   67.0
78368  560583000512                      21                   10.0
78369  560609000342                      54                   54.5
78370  560609000363                      49                   54.5
78371  560609000401                      18                   30.0
78372  560624000343                      62                   32.0
78373  560624000344                     266                   52.0
78374  560624000345                      93                   52.0
78375  560624000346                      70                   67.0
78376  560624000347                      84                   52.0

[78377 rows x 3 columns]

In [25]:
data_test_reading.shape

(78377, 3)

# Math Scores

In [26]:
data_math = pd.read_csv('data/math_adjust.csv', error_bad_lines=False, quoting=csv.QUOTE_NONE, encoding='utf-8')

data_math

            NCESSCH  ALL_MTH00NUMVALID_1314 ALL_MTH00PCTPROF_1314
0       10000500870                     637                    23
1       10000500871                     301                    18
2       10000500879                     673                    41
3       10000500889                     791                    42
4       10000600193                     443                    39
5       10000600872                     284                    36
6       10000600876                      39                 40-49
7       10000600877                     477                    48
8       10000600878                     157                 10-14
9       10000600880                     244                    46
10      10000600883                     119                 20-24
11      10000601434                     243                    39
12      10000601585                     105                 10-14
13      10000601685                     169                 50-54
14      10000601812                     444                    37
15      10000602209                     270                    35
16      10000700091                     192                 50-54
17      10000700248                     305                    72
18      10000700251                     664                    40
19      10000700337                    1173                    60
20      10000700342                     228                    66
21      10000701422                     856                    55
22      10000701456                     400                    44
23      10000701483                     355                    66
24      10000701738                     302                    57
25      10000701739                     217                    45
26      10000701740                     280                    56
27      10000701741                     846                    58
28      10000701742                     274                    59
29      10000701743                     166                 50-54
...             ...                     ...                   ...
80095  560570000362                     105                 40-44
80096  560570000510                      54                 20-29
80097  560576200164                      12                  LT50
80098  560576200285                     392                    34
80099  560576200324                     161                 30-34
80100  560576200326                       2                    PS
80101  560576200329                       4                    PS
80102  560576200332                      66                 40-44
80103  560576200399                     383                    34
80104  560576200424                      86                 40-44
80105  560576200425                     110                 40-44
80106  560576200439                      83                 40-44
80107  560576200528                       1                    PS
80108  560582000393                      40                 60-69
80109  560583000289                     423                    44
80110  560583000335                     113                 50-54
80111  560583000336                     441                    50
80112  560583000337                      19                 60-79
80113  560583000339                      17                 60-79
80114  560583000340                       3                    PS
80115  560583000341                      93                 60-64
80116  560583000512                      21                  LE20
80117  560609000342                      55                 40-49
80118  560609000363                      48                 50-59
80119  560609000401                      21                 21-39
80120  560624000343                      78                 35-39
80121  560624000344                     276                    40
80122  560624000345                     109                 50-54
80123  560624000346                      62                 65-69
80124  560624000347                      94                 35-39

[80125 rows x 3 columns]

In [27]:
data_math['NCESSCH'].dtype

dtype('int64')

In [28]:
data_math['ALL_MTH00PCTPROF_1314'][0:8]

0       23
1       18
2       41
3       42
4       39
5       36
6    40-49
7       48
Name: ALL_MTH00PCTPROF_1314, dtype: object

In [29]:
data_math = data_math[data_math['ALL_MTH00PCTPROF_1314'] != 'PS']

In [30]:
data_math

            NCESSCH  ALL_MTH00NUMVALID_1314 ALL_MTH00PCTPROF_1314
0       10000500870                     637                    23
1       10000500871                     301                    18
2       10000500879                     673                    41
3       10000500889                     791                    42
4       10000600193                     443                    39
5       10000600872                     284                    36
6       10000600876                      39                 40-49
7       10000600877                     477                    48
8       10000600878                     157                 10-14
9       10000600880                     244                    46
10      10000600883                     119                 20-24
11      10000601434                     243                    39
12      10000601585                     105                 10-14
13      10000601685                     169                 50-54
14      10000601812                     444                    37
15      10000602209                     270                    35
16      10000700091                     192                 50-54
17      10000700248                     305                    72
18      10000700251                     664                    40
19      10000700337                    1173                    60
20      10000700342                     228                    66
21      10000701422                     856                    55
22      10000701456                     400                    44
23      10000701483                     355                    66
24      10000701738                     302                    57
25      10000701739                     217                    45
26      10000701740                     280                    56
27      10000701741                     846                    58
28      10000701742                     274                    59
29      10000701743                     166                 50-54
...             ...                     ...                   ...
80091  560569500361                     506                    58
80092  560569500397                     113                 75-79
80093  560569500474                     142                 70-74
80094  560570000323                      20                 21-39
80095  560570000362                     105                 40-44
80096  560570000510                      54                 20-29
80097  560576200164                      12                  LT50
80098  560576200285                     392                    34
80099  560576200324                     161                 30-34
80102  560576200332                      66                 40-44
80103  560576200399                     383                    34
80104  560576200424                      86                 40-44
80105  560576200425                     110                 40-44
80106  560576200439                      83                 40-44
80108  560582000393                      40                 60-69
80109  560583000289                     423                    44
80110  560583000335                     113                 50-54
80111  560583000336                     441                    50
80112  560583000337                      19                 60-79
80113  560583000339                      17                 60-79
80115  560583000341                      93                 60-64
80116  560583000512                      21                  LE20
80117  560609000342                      55                 40-49
80118  560609000363                      48                 50-59
80119  560609000401                      21                 21-39
80120  560624000343                      78                 35-39
80121  560624000344                     276                    40
80122  560624000345                     109                 50-54
80123  560624000346                      62                 65-69
80124  560624000347                      94                 35-39

[76154 rows x 3 columns]

In [31]:
data_math0 = data_math.copy()

lt_rows = data_math0['ALL_MTH00PCTPROF_1314'].str.contains('LT')
le_rows = data_math0['ALL_MTH00PCTPROF_1314'].str.contains('LE')
ge_rows = data_math0['ALL_MTH00PCTPROF_1314'].str.contains('GE')

data_math0.replace({'ALL_MTH00PCTPROF_1314': {r'^(LE|GE|LT*)': ''}}, regex=True, inplace=True)

In [32]:
data_math0

            NCESSCH  ALL_MTH00NUMVALID_1314 ALL_MTH00PCTPROF_1314
0       10000500870                     637                    23
1       10000500871                     301                    18
2       10000500879                     673                    41
3       10000500889                     791                    42
4       10000600193                     443                    39
5       10000600872                     284                    36
6       10000600876                      39                 40-49
7       10000600877                     477                    48
8       10000600878                     157                 10-14
9       10000600880                     244                    46
10      10000600883                     119                 20-24
11      10000601434                     243                    39
12      10000601585                     105                 10-14
13      10000601685                     169                 50-54
14      10000601812                     444                    37
15      10000602209                     270                    35
16      10000700091                     192                 50-54
17      10000700248                     305                    72
18      10000700251                     664                    40
19      10000700337                    1173                    60
20      10000700342                     228                    66
21      10000701422                     856                    55
22      10000701456                     400                    44
23      10000701483                     355                    66
24      10000701738                     302                    57
25      10000701739                     217                    45
26      10000701740                     280                    56
27      10000701741                     846                    58
28      10000701742                     274                    59
29      10000701743                     166                 50-54
...             ...                     ...                   ...
80091  560569500361                     506                    58
80092  560569500397                     113                 75-79
80093  560569500474                     142                 70-74
80094  560570000323                      20                 21-39
80095  560570000362                     105                 40-44
80096  560570000510                      54                 20-29
80097  560576200164                      12                    50
80098  560576200285                     392                    34
80099  560576200324                     161                 30-34
80102  560576200332                      66                 40-44
80103  560576200399                     383                    34
80104  560576200424                      86                 40-44
80105  560576200425                     110                 40-44
80106  560576200439                      83                 40-44
80108  560582000393                      40                 60-69
80109  560583000289                     423                    44
80110  560583000335                     113                 50-54
80111  560583000336                     441                    50
80112  560583000337                      19                 60-79
80113  560583000339                      17                 60-79
80115  560583000341                      93                 60-64
80116  560583000512                      21                    20
80117  560609000342                      55                 40-49
80118  560609000363                      48                 50-59
80119  560609000401                      21                 21-39
80120  560624000343                      78                 35-39
80121  560624000344                     276                    40
80122  560624000345                     109                 50-54
80123  560624000346                      62                 65-69
80124  560624000347                      94                 35-39

[76154 rows x 3 columns]

In [33]:
data_math2 = data_math0.copy()

data_math2.loc[lt_rows, ('ALL_MTH00PCTPROF_1314')] = data_math0['ALL_MTH00PCTPROF_1314'][lt_rows].astype(float) / 2
data_math2.loc[le_rows, ('ALL_MTH00PCTPROF_1314')] = data_math0['ALL_MTH00PCTPROF_1314'][le_rows].astype(float) / 2
data_math2.loc[ge_rows, ('ALL_MTH00PCTPROF_1314')] = (data_math0['ALL_MTH00PCTPROF_1314'][ge_rows].astype(float) + 100) / 2

In [34]:
data_math2

            NCESSCH  ALL_MTH00NUMVALID_1314 ALL_MTH00PCTPROF_1314
0       10000500870                     637                    23
1       10000500871                     301                    18
2       10000500879                     673                    41
3       10000500889                     791                    42
4       10000600193                     443                    39
5       10000600872                     284                    36
6       10000600876                      39                 40-49
7       10000600877                     477                    48
8       10000600878                     157                 10-14
9       10000600880                     244                    46
10      10000600883                     119                 20-24
11      10000601434                     243                    39
12      10000601585                     105                 10-14
13      10000601685                     169                 50-54
14      10000601812                     444                    37
15      10000602209                     270                    35
16      10000700091                     192                 50-54
17      10000700248                     305                    72
18      10000700251                     664                    40
19      10000700337                    1173                    60
20      10000700342                     228                    66
21      10000701422                     856                    55
22      10000701456                     400                    44
23      10000701483                     355                    66
24      10000701738                     302                    57
25      10000701739                     217                    45
26      10000701740                     280                    56
27      10000701741                     846                    58
28      10000701742                     274                    59
29      10000701743                     166                 50-54
...             ...                     ...                   ...
80091  560569500361                     506                    58
80092  560569500397                     113                 75-79
80093  560569500474                     142                 70-74
80094  560570000323                      20                 21-39
80095  560570000362                     105                 40-44
80096  560570000510                      54                 20-29
80097  560576200164                      12                    25
80098  560576200285                     392                    34
80099  560576200324                     161                 30-34
80102  560576200332                      66                 40-44
80103  560576200399                     383                    34
80104  560576200424                      86                 40-44
80105  560576200425                     110                 40-44
80106  560576200439                      83                 40-44
80108  560582000393                      40                 60-69
80109  560583000289                     423                    44
80110  560583000335                     113                 50-54
80111  560583000336                     441                    50
80112  560583000337                      19                 60-79
80113  560583000339                      17                 60-79
80115  560583000341                      93                 60-64
80116  560583000512                      21                    10
80117  560609000342                      55                 40-49
80118  560609000363                      48                 50-59
80119  560609000401                      21                 21-39
80120  560624000343                      78                 35-39
80121  560624000344                     276                    40
80122  560624000345                     109                 50-54
80123  560624000346                      62                 65-69
80124  560624000347                      94                 35-39

[76154 rows x 3 columns]

In [35]:
data_math3 = data_math2.copy()

a = data_math2['ALL_MTH00PCTPROF_1314'].astype(str).str.contains('-')

data_math3.loc[a, ('ALL_MTH00PCTPROF_1314')] = data_math2['ALL_MTH00PCTPROF_1314'][a].str.split('-', expand=True).astype(float).mean(axis=1)

In [36]:
data_math3

            NCESSCH  ALL_MTH00NUMVALID_1314 ALL_MTH00PCTPROF_1314
0       10000500870                     637                    23
1       10000500871                     301                    18
2       10000500879                     673                    41
3       10000500889                     791                    42
4       10000600193                     443                    39
5       10000600872                     284                    36
6       10000600876                      39                  44.5
7       10000600877                     477                    48
8       10000600878                     157                    12
9       10000600880                     244                    46
10      10000600883                     119                    22
11      10000601434                     243                    39
12      10000601585                     105                    12
13      10000601685                     169                    52
14      10000601812                     444                    37
15      10000602209                     270                    35
16      10000700091                     192                    52
17      10000700248                     305                    72
18      10000700251                     664                    40
19      10000700337                    1173                    60
20      10000700342                     228                    66
21      10000701422                     856                    55
22      10000701456                     400                    44
23      10000701483                     355                    66
24      10000701738                     302                    57
25      10000701739                     217                    45
26      10000701740                     280                    56
27      10000701741                     846                    58
28      10000701742                     274                    59
29      10000701743                     166                    52
...             ...                     ...                   ...
80091  560569500361                     506                    58
80092  560569500397                     113                    77
80093  560569500474                     142                    72
80094  560570000323                      20                    30
80095  560570000362                     105                    42
80096  560570000510                      54                  24.5
80097  560576200164                      12                    25
80098  560576200285                     392                    34
80099  560576200324                     161                    32
80102  560576200332                      66                    42
80103  560576200399                     383                    34
80104  560576200424                      86                    42
80105  560576200425                     110                    42
80106  560576200439                      83                    42
80108  560582000393                      40                  64.5
80109  560583000289                     423                    44
80110  560583000335                     113                    52
80111  560583000336                     441                    50
80112  560583000337                      19                  69.5
80113  560583000339                      17                  69.5
80115  560583000341                      93                    62
80116  560583000512                      21                    10
80117  560609000342                      55                  44.5
80118  560609000363                      48                  54.5
80119  560609000401                      21                    30
80120  560624000343                      78                    37
80121  560624000344                     276                    40
80122  560624000345                     109                    52
80123  560624000346                      62                    67
80124  560624000347                      94                    37

[76154 rows x 3 columns]

In [37]:
data_math3.to_csv('data/final_data/math_final.csv', index=False, encoding='utf-8')

In [38]:
data_test_math = pd.read_csv('data/final_data/math_final.csv')
data_test_math

            NCESSCH  ALL_MTH00NUMVALID_1314  ALL_MTH00PCTPROF_1314
0       10000500870                     637                   23.0
1       10000500871                     301                   18.0
2       10000500879                     673                   41.0
3       10000500889                     791                   42.0
4       10000600193                     443                   39.0
5       10000600872                     284                   36.0
6       10000600876                      39                   44.5
7       10000600877                     477                   48.0
8       10000600878                     157                   12.0
9       10000600880                     244                   46.0
10      10000600883                     119                   22.0
11      10000601434                     243                   39.0
12      10000601585                     105                   12.0
13      10000601685                     169                   52.0
14      10000601812                     444                   37.0
15      10000602209                     270                   35.0
16      10000700091                     192                   52.0
17      10000700248                     305                   72.0
18      10000700251                     664                   40.0
19      10000700337                    1173                   60.0
20      10000700342                     228                   66.0
21      10000701422                     856                   55.0
22      10000701456                     400                   44.0
23      10000701483                     355                   66.0
24      10000701738                     302                   57.0
25      10000701739                     217                   45.0
26      10000701740                     280                   56.0
27      10000701741                     846                   58.0
28      10000701742                     274                   59.0
29      10000701743                     166                   52.0
...             ...                     ...                    ...
76124  560569500361                     506                   58.0
76125  560569500397                     113                   77.0
76126  560569500474                     142                   72.0
76127  560570000323                      20                   30.0
76128  560570000362                     105                   42.0
76129  560570000510                      54                   24.5
76130  560576200164                      12                   25.0
76131  560576200285                     392                   34.0
76132  560576200324                     161                   32.0
76133  560576200332                      66                   42.0
76134  560576200399                     383                   34.0
76135  560576200424                      86                   42.0
76136  560576200425                     110                   42.0
76137  560576200439                      83                   42.0
76138  560582000393                      40                   64.5
76139  560583000289                     423                   44.0
76140  560583000335                     113                   52.0
76141  560583000336                     441                   50.0
76142  560583000337                      19                   69.5
76143  560583000339                      17                   69.5
76144  560583000341                      93                   62.0
76145  560583000512                      21                   10.0
76146  560609000342                      55                   44.5
76147  560609000363                      48                   54.5
76148  560609000401                      21                   30.0
76149  560624000343                      78                   37.0
76150  560624000344                     276                   40.0
76151  560624000345                     109                   52.0
76152  560624000346                      62                   67.0
76153  560624000347                      94                   37.0

[76154 rows x 3 columns]

In [39]:
data_test_math.shape

(76154, 3)

# Income Data
## Possibly remove income data since it is by county

In [40]:
# data_income = pd.read_excel('data/income.xls', dtype={'County FIPS Code': np.str} )
# data_income

In [41]:
# data_income.shape

In [42]:
# data_income["CONUM"] = data_income["State FIPS Code"].map(str) + data_income["County FIPS Code"].map(str)

In [43]:
# data_income

In [44]:
# cols = data_income.columns.tolist()
# cols = cols[-1:] + cols[:-1]
# data_income = data_income[cols]

# data_income

In [45]:
# data_income.to_csv('data/final_data/income_final.csv', index=False, encoding='utf-8')

In [46]:
# data_test_income = pd.read_csv('data/final_data/income_final.csv', error_bad_lines=False, quoting=csv.QUOTE_NONE, encoding='utf-8')
# data_test_income

In [47]:
# data_income.shape

# School District Poverty

In [48]:
data_school_poverty = pd.read_excel('data/school_district_poverty.xls', dtype={'District ID': np.str})

rn_cols = {'Estimated Total Population':'district_total_pop', 'Estimated Population 5-17': 'est_pop_5-17',
          'Estimated number of relevant children 5 to 17 years old in poverty who are related to the householder': 
          'est_pop_5-17_household'}

data_school_poverty = data_school_poverty.rename(columns = rn_cols)

data_school_poverty

,State Postal Code,State FIPS Code,District ID,Name,district_total_pop,est_pop_5-17,est_pop_5-17_household
0,AL,1,00190,Alabaster City School District,32139,6502,974
1,AL,1,00005,Albertville City School District,21494,4022,1581
2,AL,1,00030,Alexander City City School District,17276,2673,961
3,AL,1,00060,Andalusia City School District,9051,1516,492
4,AL,1,00090,Anniston City School District,22599,3289,1058
5,AL,1,00100,Arab City School District,8227,1495,277
6,AL,1,00120,Athens City School District,24008,3885,714
7,AL,1,00180,Attalla City School District,5996,957,298
8,AL,1,00210,Auburn City School District,58705,7119,1283
9,AL,1,00240,Autauga County School District,55395,10622,1832
10,AL,1,00270,Baldwin County School District,200111,33171,6118
11,AL,1,00300,Barbour County School District,14026,1782,686
12,AL,1,00330,Bessemer City School District,27565,4767,2227
13,AL,1,00360,Bibb County School District,22506,3528,866
14,AL,1,00390,Birmingham City School District,213072,30731,14908
15,AL,1,00420,Blount County School District,51111,9067,2023
16,AL,1,00012,Boaz City School District,9603,1743,479
17,AL,1,00450,Brewton City School District,5318,867,271
18,AL,1,00480,Bullock County School District,10764,1629,649
19,AL,1,00510,Butler County School District,20296,3551,1235
20,AL,1,00540,Calhoun County School District,56104,9901,2031
21,AL,1,00600,Chambers County School District,27626,4293,1175
22,AL,1,00630,Cherokee County School District,26037,4053,1019
23,AL,1,00188,Chickasaw City School District,6135,1027,473
24,AL,1,00660,Chilton County School District,43931,7812,2070
25,AL,1,00690,Choctaw County School District,13323,2084,592
26,AL,1,00720,Clarke County School District,19257,3265,1090
27,AL,1,00750,Clay County School District,13552,2204,581
28,AL,1,00780,Cleburne County School District,14715,2586,589
29,AL,1,00810,Coffee County School District,18985,3339,661
...,...,...,...,...,...,...,...
13457,WY,56,02990,Goshen County School District 1,13427,1941,319
13458,WY,56,03310,Hot Springs County School District 1,4816,789,107
13459,WY,56,03770,Johnson County School District 1,8573,1392,144
13460,WY,56,01980,Laramie County School District 1,90577,15273,1890
13461,WY,56,04120,Laramie County School District 2,5812,1130,156
13462,WY,56,04030,Lincoln County School District 1,3993,660,33
13463,WY,56,04060,Lincoln County School District 2,13750,2953,360
13464,WY,56,04510,Natrona County School District 1,81624,13956,1628
13465,WY,56,04230,Niobrara County School District 1,2500,297,49
13466,WY,56,05160,Park County School District 1,12246,1881,256
13467,WY,56,04380,Park County School District 16,811,121,5
13468,WY,56,02070,Park County School District 6,15513,2281,334
13469,WY,56,05090,Platte County School District 1,7362,1156,171
13470,WY,56,03180,Platte County School District 2,1487,221,35
13471,WY,56,05690,Sheridan County School District 1,4768,840,52
13472,WY,56,05695,Sheridan County School District 2,24822,3859,476
13473,WY,56,05680,Sheridan County School District 3,442,86,4
13474,WY,56,04860,Sublette County School District 1,6794,1248,71
13475,WY,56,01260,Sublette County School District 9,4087,765,59
13476,WY,56,05302,Sweetwater County School District 1,30869,5929,670
13477,WY,56,05762,Sweetwater County School District 2,14032,2941,222
13478,WY,56,05830,Teton County School District 1,22930,3054,261
13479,WY,56,02760,Uinta County School District 1,14470,3109,368
13480,WY,56,04500,Uinta County School District 4,3219,748,59
13481,WY,56,04260,Uinta County School District 6,3215,776,49
13482,WY,56,06240,Washakie County School District 1,7608,1435,194
13483,WY,56,05820,Washakie County School District 2,714,100,20
13484,WY,56,04830,Weston County School District 1,5681,831,165
13485,WY,56,06090,Weston County School District 7,1520,254,25
13486,PR,72,00030,Puerto Rico,3548397,585381,332910

In [49]:
data_school_poverty['LEAID'] = data_school_poverty['State FIPS Code'].map(str) + data_school_poverty['District ID']
data_school_poverty['child_poverty'] = data_school_poverty['est_pop_5-17_household'] / data_school_poverty['est_pop_5-17']

In [50]:
data_school_poverty

,State Postal Code,State FIPS Code,District ID,Name,district_total_pop,est_pop_5-17,est_pop_5-17_household,LEAID,child_poverty
0,AL,1,00190,Alabaster City School District,32139,6502,974,100190,0.149800
1,AL,1,00005,Albertville City School District,21494,4022,1581,100005,0.393088
2,AL,1,00030,Alexander City City School District,17276,2673,961,100030,0.359521
3,AL,1,00060,Andalusia City School District,9051,1516,492,100060,0.324538
4,AL,1,00090,Anniston City School District,22599,3289,1058,100090,0.321678
5,AL,1,00100,Arab City School District,8227,1495,277,100100,0.185284
6,AL,1,00120,Athens City School District,24008,3885,714,100120,0.183784
7,AL,1,00180,Attalla City School District,5996,957,298,100180,0.311390
8,AL,1,00210,Auburn City School District,58705,7119,1283,100210,0.180222
9,AL,1,00240,Autauga County School District,55395,10622,1832,100240,0.172472
10,AL,1,00270,Baldwin County School District,200111,33171,6118,100270,0.184438
11,AL,1,00300,Barbour County School District,14026,1782,686,100300,0.384961
12,AL,1,00330,Bessemer City School District,27565,4767,2227,100330,0.467170
13,AL,1,00360,Bibb County School District,22506,3528,866,100360,0.245465
14,AL,1,00390,Birmingham City School District,213072,30731,14908,100390,0.485113
15,AL,1,00420,Blount County School District,51111,9067,2023,100420,0.223117
16,AL,1,00012,Boaz City School District,9603,1743,479,100012,0.274814
17,AL,1,00450,Brewton City School District,5318,867,271,100450,0.312572
18,AL,1,00480,Bullock County School District,10764,1629,649,100480,0.398404
19,AL,1,00510,Butler County School District,20296,3551,1235,100510,0.347789
20,AL,1,00540,Calhoun County School District,56104,9901,2031,100540,0.205131
21,AL,1,00600,Chambers County School District,27626,4293,1175,100600,0.273701
22,AL,1,00630,Cherokee County School District,26037,4053,1019,100630,0.251419
23,AL,1,00188,Chickasaw City School District,6135,1027,473,100188,0.460565
24,AL,1,00660,Chilton County School District,43931,7812,2070,100660,0.264977
25,AL,1,00690,Choctaw County School District,13323,2084,592,100690,0.284069
26,AL,1,00720,Clarke County School District,19257,3265,1090,100720,0.333844
27,AL,1,00750,Clay County School District,13552,2204,581,100750,0.263612
28,AL,1,00780,Cleburne County School District,14715,2586,589,100780,0.227765
29,AL,1,00810,Coffee County School District,18985,3339,661,100810,0.197963
...,...,...,...,...,...,...,...,...,...
13457,WY,56,02990,Goshen County School District 1,13427,1941,319,5602990,0.164348
13458,WY,56,03310,Hot Springs County School District 1,4816,789,107,5603310,0.135615
13459,WY,56,03770,Johnson County School District 1,8573,1392,144,5603770,0.103448
13460,WY,56,01980,Laramie County School District 1,90577,15273,1890,5601980,0.123748
13461,WY,56,04120,Laramie County School District 2,5812,1130,156,5604120,0.138053
13462,WY,56,04030,Lincoln County School District 1,3993,660,33,5604030,0.050000
13463,WY,56,04060,Lincoln County School District 2,13750,2953,360,5604060,0.121910
13464,WY,56,04510,Natrona County School District 1,81624,13956,1628,5604510,0.116652
13465,WY,56,04230,Niobrara County School District 1,2500,297,49,5604230,0.164983
13466,WY,56,05160,Park County School District 1,12246,1881,256,5605160,0.136098
13467,WY,56,04380,Park County School District 16,811,121,5,5604380,0.041322
13468,WY,56,02070,Park County School District 6,15513,2281,334,5602070,0.146427
13469,WY,56,05090,Platte County School District 1,7362,1156,171,5605090,0.147924
13470,WY,56,03180,Platte County School District 2,1487,221,35,5603180,0.158371
13471,WY,56,05690,Sheridan County School District 1,4768,840,52,5605690,0.061905
13472,WY,56,05695,Sheridan County School District 2,24822,3859,476,5605695,0.123348
13473,WY,56,05680,Sheridan County School District 3,442,86,4,5605680,0.046512
13474,WY,56,04860,Sublette County School District 1,6794,1248,71,5604860,0.056891
13475,WY,56,01260,Sublette County School District 9,4087,765,59,5601260,0.077124
13476,WY,56,05302,Sweetwater County School District 1,30869,5929,670,5605302,0.113004
13477,WY,56,05762,Sweetwater County School District 2,14032,2941,222,5605762,0.075485
13478,WY,56,05830,Teton County School District 1,22930,3054,261,5605830,0.085462
13479,WY,56,02760,Uinta County School District 1,14470,3109,368,5602760,0.118366
13480,WY,56,04500,Uinta County School District 4,3219,748,59,5604500,0.078877
13481,WY,56,04260,Uinta County School District 6,3215,776,49,5604260,0.063144
13482,WY,56,06240,Washakie County School District 1,7608,1435,194,5606240,0.135192
13483,WY,56,05820,Washakie County School District 2,714,100,20,5605820,0.200000
13484,WY,56,04830,Weston County School District 1,5681,831,165,5604830,0.198556
13485,WY,56,06090,Weston County School District 7,1520,254,25,5606090,0.098425
13486,PR,72,00030,Puerto Rico,3548397,585381,332910,7200030,0.568707

In [51]:
data_school_poverty.to_csv('data/final_data/school_district_poverty_final.csv', index=False, encoding='utf-8')
data_school_poverty

,State Postal Code,State FIPS Code,District ID,Name,district_total_pop,est_pop_5-17,est_pop_5-17_household,LEAID,child_poverty
0,AL,1,00190,Alabaster City School District,32139,6502,974,100190,0.149800
1,AL,1,00005,Albertville City School District,21494,4022,1581,100005,0.393088
2,AL,1,00030,Alexander City City School District,17276,2673,961,100030,0.359521
3,AL,1,00060,Andalusia City School District,9051,1516,492,100060,0.324538
4,AL,1,00090,Anniston City School District,22599,3289,1058,100090,0.321678
5,AL,1,00100,Arab City School District,8227,1495,277,100100,0.185284
6,AL,1,00120,Athens City School District,24008,3885,714,100120,0.183784
7,AL,1,00180,Attalla City School District,5996,957,298,100180,0.311390
8,AL,1,00210,Auburn City School District,58705,7119,1283,100210,0.180222
9,AL,1,00240,Autauga County School District,55395,10622,1832,100240,0.172472
10,AL,1,00270,Baldwin County School District,200111,33171,6118,100270,0.184438
11,AL,1,00300,Barbour County School District,14026,1782,686,100300,0.384961
12,AL,1,00330,Bessemer City School District,27565,4767,2227,100330,0.467170
13,AL,1,00360,Bibb County School District,22506,3528,866,100360,0.245465
14,AL,1,00390,Birmingham City School District,213072,30731,14908,100390,0.485113
15,AL,1,00420,Blount County School District,51111,9067,2023,100420,0.223117
16,AL,1,00012,Boaz City School District,9603,1743,479,100012,0.274814
17,AL,1,00450,Brewton City School District,5318,867,271,100450,0.312572
18,AL,1,00480,Bullock County School District,10764,1629,649,100480,0.398404
19,AL,1,00510,Butler County School District,20296,3551,1235,100510,0.347789
20,AL,1,00540,Calhoun County School District,56104,9901,2031,100540,0.205131
21,AL,1,00600,Chambers County School District,27626,4293,1175,100600,0.273701
22,AL,1,00630,Cherokee County School District,26037,4053,1019,100630,0.251419
23,AL,1,00188,Chickasaw City School District,6135,1027,473,100188,0.460565
24,AL,1,00660,Chilton County School District,43931,7812,2070,100660,0.264977
25,AL,1,00690,Choctaw County School District,13323,2084,592,100690,0.284069
26,AL,1,00720,Clarke County School District,19257,3265,1090,100720,0.333844
27,AL,1,00750,Clay County School District,13552,2204,581,100750,0.263612
28,AL,1,00780,Cleburne County School District,14715,2586,589,100780,0.227765
29,AL,1,00810,Coffee County School District,18985,3339,661,100810,0.197963
...,...,...,...,...,...,...,...,...,...
13457,WY,56,02990,Goshen County School District 1,13427,1941,319,5602990,0.164348
13458,WY,56,03310,Hot Springs County School District 1,4816,789,107,5603310,0.135615
13459,WY,56,03770,Johnson County School District 1,8573,1392,144,5603770,0.103448
13460,WY,56,01980,Laramie County School District 1,90577,15273,1890,5601980,0.123748
13461,WY,56,04120,Laramie County School District 2,5812,1130,156,5604120,0.138053
13462,WY,56,04030,Lincoln County School District 1,3993,660,33,5604030,0.050000
13463,WY,56,04060,Lincoln County School District 2,13750,2953,360,5604060,0.121910
13464,WY,56,04510,Natrona County School District 1,81624,13956,1628,5604510,0.116652
13465,WY,56,04230,Niobrara County School District 1,2500,297,49,5604230,0.164983
13466,WY,56,05160,Park County School District 1,12246,1881,256,5605160,0.136098
13467,WY,56,04380,Park County School District 16,811,121,5,5604380,0.041322
13468,WY,56,02070,Park County School District 6,15513,2281,334,5602070,0.146427
13469,WY,56,05090,Platte County School District 1,7362,1156,171,5605090,0.147924
13470,WY,56,03180,Platte County School District 2,1487,221,35,5603180,0.158371
13471,WY,56,05690,Sheridan County School District 1,4768,840,52,5605690,0.061905
13472,WY,56,05695,Sheridan County School District 2,24822,3859,476,5605695,0.123348
13473,WY,56,05680,Sheridan County School District 3,442,86,4,5605680,0.046512
13474,WY,56,04860,Sublette County School District 1,6794,1248,71,5604860,0.056891
13475,WY,56,01260,Sublette County School District 9,4087,765,59,5601260,0.077124
13476,WY,56,05302,Sweetwater County School District 1,30869,5929,670,5605302,0.113004
13477,WY,56,05762,Sweetwater County School District 2,14032,2941,222,5605762,0.075485
13478,WY,56,05830,Teton County School District 1,22930,3054,261,5605830,0.085462
13479,WY,56,02760,Uinta County School District 1,14470,3109,368,5602760,0.118366
13480,WY,56,04500,Uinta County School District 4,3219,748,59,5604500,0.078877
13481,WY,56,04260,Uinta County School District 6,3215,776,49,5604260,0.063144
13482,WY,56,06240,Washakie County School District 1,7608,1435,194,5606240,0.135192
13483,WY,56,05820,Washakie County School District 2,714,100,20,5605820,0.200000
13484,WY,56,04830,Weston County School District 1,5681,831,165,5604830,0.198556
13485,WY,56,06090,Weston County School District 7,1520,254,25,5606090,0.098425
13486,PR,72,00030,Puerto Rico,3548397,585381,332910,7200030,0.568707

In [ ]:
data_school_poverty.shape

# Fiscal Data

In [52]:
data_fiscal = pd.read_csv('data/school_district_fiscal.txt', sep=None)

D:\Programs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [53]:
data_fiscal

,LEAID,CENSUSID,FIPST,CONUM,CSA,CBSA,NAME,STNAME,STABBR,SCHLEV,...,FL_31F,FL_41F,FL_61V,FL_66V,FL_W01,FL_W31,FL_W61,FL_HR1,FL_HE1,FL_HE2
0,0100002,N,1,1101,N,33860,ALABAMA YOUTH SERVICES,Alabama,AL,N,...,M,M,M,M,M,M,M,M,M,M
1,0100005,01504840100000,1,1095,290,10700,ALBERTVILLE CITY,Alabama,AL,03,...,R,I,M,M,R,R,R,M,M,M
2,0100006,01504800100000,1,1095,290,10700,MARSHALL COUNTY,Alabama,AL,03,...,R,I,M,M,R,R,R,R,R,R
3,0100007,01503740100000,1,1073,142,13820,HOOVER CITY,Alabama,AL,03,...,R,I,M,M,R,R,R,M,M,M
4,0100008,01504530100000,1,1089,290,26620,MADISON CITY,Alabama,AL,03,...,R,I,M,M,R,R,R,M,M,M
5,0100009,N,1,1121,142,45180,AL INST DEAF AND BLIND,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
6,0100011,01503710100000,1,1073,142,13820,LEEDS CITY,Alabama,AL,03,...,R,I,M,M,R,R,R,M,M,M
7,0100012,01504810100000,1,1095,290,10700,BOAZ CITY,Alabama,AL,03,...,R,I,M,M,R,R,R,M,M,M
8,0100013,01503710200000,1,1073,142,13820,TRUSSVILLE CITY,Alabama,AL,03,...,R,I,M,M,R,R,R,M,M,M
9,0100015,N,1,1073,142,13820,SAFETYNET ACADEMY,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
10,0100016,N,1,1125,N,46220,BRYCE ADOLESCENT SCHOOL,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
11,0100018,N,1,1073,142,13820,ALABAMA SCHOOL OF FINE ARTS,Alabama,AL,N,...,M,M,M,M,M,M,M,M,M,M
12,0100019,N,1,1073,142,13820,UCP OF GREATER BIRMINGHAM,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
13,0100020,N,1,1125,N,46220,BOYD SCHOOL,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
14,0100021,N,1,1125,N,46220,BREWERS PORCH CHILDRENS CENTER,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
15,0100022,N,1,1079,290,19460,THREE SPRINGS COURTLAND SCH,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
16,0100023,N,1,1089,290,26620,THREE SPRINGS MADISON SCH,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
17,0100024,N,1,1089,290,26620,THREE SPRINGS NEW BEGINNINGS,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
18,0100026,N,1,1087,N,N,SEQUEL TSI TUSKEEGEE LLC,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
19,0100028,N,1,1087,N,N,THREE SPRINGS NEW TUSKEGEE,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
20,0100029,N,1,1089,290,26620,THREE SPRINGS NEW DIRECTION,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
21,0100030,01506200200000,1,1123,N,N,ALEXANDER CITY,Alabama,AL,03,...,R,I,M,M,R,R,R,M,M,M
22,0100032,N,1,1117,142,13820,THE BRIDGE,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
23,0100033,N,1,1073,142,13820,GLENWOOD MENTAL HEALTH SERVICE,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
24,0100035,N,1,1097,380,33660,LEARNING TREE INC,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
25,0100036,N,1,1081,194,12220,LEE CO YOUTH DEVELOPMENT CTR,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
26,0100037,N,1,1097,380,33660,BAY POINT CENTER,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
27,0100038,N,1,1031,222,21460,PATHWAY INC,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
28,0100039,N,1,1073,142,13820,PRESBYTERIAN HOME FOR CHILDREN,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
29,0100040,N,1,1101,N,33860,BRANTWOOD CHILDREN'S HOME,Alabama,AL,N,...,N,N,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18599,5604030,51501200100000,56,56023,N,N,LINCOLN COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18600,5604060,51501290100000,56,56023,N,N,LINCOLN COUNTY SCHOOL DISTRICT #2,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18601,5604120,51501100700000,56,56021,N,16940,LARAMIE COUNTY SCHOOL DISTRICT #2,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18602,5604230,51501400100000,56,56027,N,N,NIOBRARA COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18603,5604260,51502100400000,56,56041,N,21740,UINTA COUNTY SCHOOL DISTRICT #6,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18604,5604380,51501500600000,56,56029,N,N,PARK COUNTY SCHOOL DISTRICT #16,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18605,5604450,51500700500000,56,56013,N,40180,FREMONT COUNTY SCHOOL DISTRICT #14,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18606,5604500,51502100200000,56,56041,N,21740,UINTA COUNTY SCHOOL DISTRICT #4,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18607,5604510,51501301200000,56,56025,N,16220,NATRONA COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18608,5604830,51502300100000,56,56045,N,N,WESTON COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18609,5604860,51501800100000,56,56035,N,N,SUBLETTE COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,I,R,R,R
18610,5605090,51501600500000,56,56031,N,N,PLATTE COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18611,5605160,51501500100000,56,56029,N,N,PARK COUNTY SCHOOL DISTRICT # 1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18612,5605220,51500701000000,56,56013,N,40180,FREMONT COUNTY SCHOOL DISTRICT #25,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18613,5605302,51501900400000,56,56037,N,40540,SWEETWATER COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18614,5605680,51501701500000,56,56033,N,43260,SHERIDAN COUNTY SCHOOL DISTRICT #3,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18615,5605690,51501701700000,56,56033,N,43260,SHERIDAN COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18616,5605695,51501700600000,56,56033,N,43260,SHERIDAN COUNTY SCHOOL DISTRICT #2,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18617,5605700,51500700900000,56,56013,N,40180,FREMONT COUNTY SCHOOL DISTRICT #24,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18618,5605762,51501900200000,56,56037,N,40540,SWEETWATER COUNTY SCHOOL DISTRICT #2,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18619,5605820,51502200300000,56,56043,N,N,WASHAKIE COUNTY SCHOOL DISTRICT #2,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18620,5605830,51502000200000,56,56039,N,27220,TETON COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18621,5606090,51502300200000,56,56045,N,N,WESTON COUNTY SCHOOL DISTRICT #7,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18622,5606240,51502200400000,56,56043,N,N,WASHAKIE COUNTY SCHOOL DISTRICT #1,Wyoming,WY,03,...,R,R,R,R,R,R,R,R,R,R
18623,5680180,51500340100000,56,56005,N,23940,NORTHEAST WYOMING BOCES,Wyoming,WY,07,...,N,N,N,N,N,N,N,N,N,N
18624,5680250,51502040100000,56,56039,N,27220,REGION V BOCES,Wyoming,WY,07,...,N,N,N,N,N,N,N,N,N,N
18625,5680251,N,56,56021,N,16940,WYOMING DEPARTMENT OF FAMILY SERVICES,Wyoming,WY,N,...,N,N,N,N,N,N,N,N,N,N
18626,5680252,N,56,56005,N,23940,YOUTH EMERGENCY SERVICES,Wyoming,WY,N,...,N,N,N,N,N,N,N,N,N,N
18627,5680253,N,56,56025,N,16220,WYOMING BEHAVIORAL INSTITUTE - ADMINISTRATION ...,Wyoming,WY,N,...,N,N,N,N,N,N,N,N,N,N
18628,5680254,N,56,56013,N,40180,SAINT STEPHEN'S INDIAN SCHOOL ADMIN OFFICE,Wyoming,WY,N,...,N,N,N,N,N,N,N,N,N,N

In [54]:
all_cols = data_fiscal.columns

drop_cols = all_cols[2:18]

In [55]:
data_fiscal = data_fiscal.drop(drop_cols, axis=1)

In [56]:
nan_cols = data_fiscal['CENSUSID'] != 'N'

data_fiscal = data_fiscal[nan_cols]

In [57]:
data_fiscal.shape

(14807, 240)

In [58]:
has_rev = (data_fiscal['TOTALREV'] >= 0) | (data_fiscal['TFEDREV'] >= 0)

data_fiscal = data_fiscal[has_rev]

In [59]:
data_fiscal = data_fiscal.drop(['CENSUSID'], axis=1)

In [60]:
data_fiscal.shape

(14397, 239)

In [61]:
data_fiscal.to_csv('data/final_data/fiscal_final.csv', index=False, encoding='utf-8')

# School Information

In [62]:
data_schinfo = pd.read_csv('sc132a.txt', sep=None, engine='python')
data_district = pd.read_csv('data/district_info.txt', sep=None, engine='python')

In [63]:
# calculating teacher salaries
data_district2 = data_district[['LEAID', 'TOTTCH']]

In [64]:
data_dir = 'data/final_data/'
data_reading=pd.read_csv(data_dir + 'reading_final.csv')
data_math=pd.read_csv(data_dir + 'math_final.csv')
data_pov=pd.read_csv(data_dir + 'school_district_poverty_final.csv')
data_fisc=pd.read_csv(data_dir + 'fiscal_final.csv', dtype={'LEAID': np.str})

In [65]:
data_schinfo

,SURVYEAR,NCESSCH,FIPST,LEAID,SCHNO,STID,SEASCH,LEANM,SCHNAM,PHONE,...,HPALM,HPALF,TR,TRALM,TRALF,TOTETH,VIRTUALSTAT,NSLPSTATUS,CHARTAUTH1,CHARTAUTH2
0,2013,10000200277,1,100002,277,210,0020,ALABAMA YOUTH SERVICES,SEQUOYAH SCH - CHALKVILLE CAMPUS,2056808574,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N
1,2013,10000201402,1,100002,1402,210,0025,ALABAMA YOUTH SERVICES,EUFAULA SCH - EUFAULA CAMPUS,3346874441,...,-2,-2,-2,-2,-2,-2,VIRTUALNO,M,N,N
2,2013,10000201667,1,100002,1667,210,0050,ALABAMA YOUTH SERVICES,CAMPS,3342153850,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N
3,2013,10000201670,1,100002,1670,210,0060,ALABAMA YOUTH SERVICES,DET CTR,3342153850,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N
4,2013,10000201705,1,100002,1705,210,0030,ALABAMA YOUTH SERVICES,WALLACE SCH - MT MEIGS CAMPUS,3342156039,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N
5,2013,10000201706,1,100002,1706,210,0040,ALABAMA YOUTH SERVICES,MCNEEL SCH - VACCA CAMPUS,2058384981,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N
6,2013,10000201876,1,100002,1876,210,0001,ALABAMA YOUTH SERVICES,ALABAMA YOUTH SERVICES,2056825300,...,-2,-2,-2,-2,-2,-2,VIRTUALNO,M,N,N
7,2013,10000500870,1,100005,870,101,0010,ALBERTVILLE CITY,ALA AVENUE MIDDLE SCH,2568782341,...,0,0,12,5,7,632,VIRTUALNO,NSLPWOPRO,N,N
8,2013,10000500871,1,100005,871,101,0020,ALBERTVILLE CITY,ALBERTVILLE HIGH SCH,2568786580,...,0,0,5,2,3,1117,VIRTUALNO,NSLPWOPRO,N,N
9,2013,10000500879,1,100005,879,101,0110,ALBERTVILLE CITY,EVANS ELEM SCH,2568787698,...,0,0,24,11,13,679,VIRTUALNO,NSLPWOPRO,N,N
10,2013,10000500889,1,100005,889,101,0200,ALBERTVILLE CITY,ALBERTVILLE ELEM SCH,2568786611,...,0,1,13,8,5,780,VIRTUALNO,NSLPWOPRO,N,N
11,2013,10000501616,1,100005,1616,101,0035,ALBERTVILLE CITY,BIG SPRING LAKE KINDERG SCH,2568787922,...,1,0,15,8,7,476,VIRTUALNO,NSLPWOPRO,N,N
12,2013,10000502150,1,100005,2150,101,0005,ALBERTVILLE CITY,ALBERTVILLE PRIMARY SCH,2568786611,...,0,0,31,15,16,1029,VIRTUALNO,NSLPWOPRO,N,N
13,2013,10000600193,1,100006,193,048,0143,MARSHALL COUNTY,KATE DUNCAN SMITH DAR MIDDLE,2567285950,...,0,0,3,1,2,439,VIRTUALNO,NSLPWOPRO,N,N
14,2013,10000600872,1,100006,872,048,0030,MARSHALL COUNTY,ASBURY SCH,2568784068,...,0,0,4,2,2,514,VIRTUALNO,NSLPWOPRO,N,N
15,2013,10000600876,1,100006,876,048,0070,MARSHALL COUNTY,CLAYSVILLE JR HIGH SCH,2565824444,...,0,0,7,5,2,138,VIRTUALNO,NSLPWOPRO,N,N
16,2013,10000600877,1,100006,877,048,0090,MARSHALL COUNTY,DOUGLAS ELEM SCH,2565934420,...,0,0,4,1,3,476,VIRTUALNO,NSLPWOPRO,N,N
17,2013,10000600878,1,100006,878,048,0100,MARSHALL COUNTY,DOUGLAS HIGH SCH,2565932810,...,0,0,0,0,0,548,VIRTUALNO,NSLPWOPRO,N,N
18,2013,10000600880,1,100006,880,048,0120,MARSHALL COUNTY,GRASSY ELEM SCH,2567532246,...,0,0,2,0,2,264,VIRTUALNO,NSLPWOPRO,N,N
19,2013,10000600883,1,100006,883,048,0140,MARSHALL COUNTY,KATE D SMITH DAR HIGH SCH,2567284238,...,0,0,1,1,0,463,VIRTUALNO,NSLPWOPRO,N,N
20,2013,10000600887,1,100006,887,048,0180,MARSHALL COUNTY,UNION GROVE ELEM SCH,2567532532,...,0,0,4,1,3,216,VIRTUALNO,NSLPWOPRO,N,N
21,2013,10000600986,1,100006,986,048,0150,MARSHALL COUNTY,MARSHALL ALT SCH,2565827554,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,NSLPWOPRO,N,N
22,2013,10000600987,1,100006,987,048,0160,MARSHALL COUNTY,MARSHALL TECH SCH,2565825629,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N
23,2013,10000601413,1,100006,1413,048,0095,MARSHALL COUNTY,ROBERT D SLOMAN PRIMARY,2565934912,...,0,0,11,4,7,504,VIRTUALNO,NSLPWOPRO,N,N
24,2013,10000601434,1,100006,1434,048,0040,MARSHALL COUNTY,BRINDLEE MT MIDDLE SCH,2567532820,...,0,0,2,1,1,258,VIRTUALNO,NSLPWOPRO,N,N
25,2013,10000601585,1,100006,1585,048,0042,MARSHALL COUNTY,BRINDLEE MT HIGH SCH,2567532800,...,0,0,2,1,1,365,VIRTUALNO,NSLPWOPRO,N,N
26,2013,10000601685,1,100006,1685,048,0145,MARSHALL COUNTY,KATE D SMITH DAR ELEM SCH,2567282226,...,0,0,17,9,8,434,VIRTUALNO,NSLPWOPRO,N,N
27,2013,10000601812,1,100006,1812,048,0105,MARSHALL COUNTY,DOUGLAS MIDDLE SCH,2565931240,...,0,1,1,1,0,454,VIRTUALNO,NSLPWOPRO,N,N
28,2013,10000602209,1,100006,2209,048,0035,MARSHALL COUNTY,ASBURY ELEMENTARY SCHOOL,2568786221,...,0,0,5,1,4,531,VIRTUALNO,NSLPWOPRO,N,N
29,2013,10000700091,1,100007,91,158,0820,HOOVER CITY,TRACE CROSSINGS ELEM SCH,2054392700,...,0,0,22,15,7,549,VIRTUALNO,NSLPWOPRO,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102785,2013,780000200002,78,7800002,2,002,37,SAINT CROIX SCHOOL DISTRICT,ALFREDO ANDREWS ELEMENTARY SCHOOL,3407781925,...,0,0,2,0,2,275,N,NSLPPRO1,N,N
102786,2013,780000200003,78,7800002,3,002,46,SAINT CROIX SCHOOL DISTRICT,ARTHUR A. RICHARDS JUNIOR HIGH SCHOOL,3407721500,...,0,0,0,0,0,418,N,NSLPPRO1,N,N
102787,2013,780000200004,78,7800002,4,002,31,SAINT CROIX SCHOOL DISTRICT,CHARLES H. EMANUEL ELEMENTARY SCHOOL,3407780511,...,0,0,0,0,0,300,N,NSLPPRO1,N,N
102788,2013,780000200006,78,7800002,6,002,34,SAINT CROIX SCHOOL DISTRICT,CLAUDE O. MARKOE ELEMENTARY SCHOOL,3407724510,...,0,0,2,1,1,297,N,NSLPPRO1,N,N
102789,2013,780000200007,78,7800002,7,002,49,SAINT CROIX SCHOOL DISTRICT,ST. CROIX EDUCATIONAL COMPLEX VOCATIONAL SCHOOL,3407782036,...,-1,-1,-1,-1,-1,-1,N,NSLPPRO1,N,N
102790,2013,780000200009,78,7800002,9,002,45,SAINT CROIX SCHOOL DISTRICT,ELENA L. CHRISTIAN JUNIOR HIGH SCCHOOL,3407734445,...,0,0,5,3,2,334,N,NSLPPRO1,N,N
102791,2013,780000200011,78,7800002,11,002,32,SAINT CROIX SCHOOL DISTRICT,EULALIE RIVERA ELEMENTARY SCHOOL,3406922121,...,0,0,1,0,1,377,N,NSLPPRO1,N,N
102792,2013,780000200013,78,7800002,13,002,50,SAINT CROIX SCHOOL DISTRICT,ST. CROIX EDUCATIONAL COMPEX HIGH SCHOOL,3407782216,...,0,1,16,6,10,1167,N,NSLPPRO1,N,N
102793,2013,780000200021,78,7800002,21,002,30,SAINT CROIX SCHOOL DISTRICT,JUANITA GARDINE ELEMENTARY SCHOOL,3407730050,...,0,0,0,0,0,394,N,NSLPPRO1,N,N
102794,2013,780000200023,78,7800002,23,002,33,SAINT CROIX SCHOOL DISTRICT,LEW MUCKLE ELEMENTARY SCHOOL,3407785286,...,0,0,4,2,2,392,N,NSLPPRO1,N,N
102795,2013,780000200028,78,7800002,28,002,36,SAINT CROIX SCHOOL DISTRICT,PEARL B. LARSEN ELEMENTARY SCHOOL,3407733070,...,1,1,0,0,0,383,N,NSLPPRO1,N,N
102796,2013,780000200029,78,7800002,29,002,43,SAINT CROIX SCHOOL DISTRICT,RICARDO RICHARDS ELEMENTARY SCCHOOL,3407780612,...,1,0,2,2,0,489,N,NSLPPRO1,N,N
102797,2013,780000200030,78,7800002,30,002,47,SAINT CROIX SCHOOL DISTRICT,SAINT CROIX CENTRAL HIGH,3407780123,...,1,0,11,8,3,1063,N,NSLPPRO1,N,N
102798,2013,780000200035,78,7800002,35,002,42,SAINT CROIX SCHOOL DISTRICT,EVELYN M. WILLIAMS ELEMENTARY SCHOOL,3407722844,...,0,0,0,0,0,348,N,NSLPPRO1,N,N
102799,2013,780000200037,78,7800002,37,002,44,SAINT CROIX SCHOOL DISTRICT,JOHN H. WOODSON JUNIOR HIGH SCHOOL,3407782710,...,0,0,1,1,0,357,N,NSLPPRO1,N,N
102800,2013,780003000005,78,7800030,5,001,27,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,CHARLOTTE AMALIE HIGH SCHOOL,3407740780,...,1,0,16,4,12,1434,N,NSLPPRO1,N,N
102801,2013,780003000008,78,7800030,8,001,11,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,LEONARD DOBER ELEMENTARY SCHOOL,3407745253,...,0,0,0,0,0,127,N,NSLPPRO1,N,N
102802,2013,780003000010,78,7800030,10,001,26,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,E. BENJAMIN OLIVER ELEMENTARY SCHOOL,3407752000,...,0,0,0,0,0,625,N,NSLPPRO1,N,N
102803,2013,780003000014,78,7800030,14,001,51,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,GUY BENJAMIN ELEMENTARY SCHOOL,3407766242,...,0,0,6,3,3,55,N,NSLPPRO1,N,N
102804,2013,780003000015,78,7800030,15,001,28,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,IVANNA EUDORA KEAN HIGH SCHOOL,3407756380,...,0,0,10,4,6,1006,N,NSLPPRO1,N,N
102805,2013,780003000018,78,7800030,18,001,18,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,JANE E. TUITT ELEMENTARY SCHOOL,3407740520,...,0,0,0,0,0,198,N,NSLPPRO1,N,N
102806,2013,780003000019,78,7800030,19,001,20,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,JOSEPH GOMEZ ELEMENTARY SCHOOL,3407754490,...,0,0,0,0,0,559,N,NSLPPRO1,N,N
102807,2013,780003000020,78,7800030,20,001,12,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,JOSEPH SIBILLY ELEMENTARY SCHOOL,3407747001,...,1,3,1,0,1,287,N,NSLPPRO1,N,N
102808,2013,780003000022,78,7800030,22,001,52,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,JULIUS E SPRAUVE,3407766336,...,0,0,4,2,2,285,N,NSLPPRO1,N,N
102809,2013,780003000024,78,7800030,24,001,15,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,LOCKHART ELEMENTARY SCHOOL,3407750820,...,0,0,3,3,0,704,N,NSLPPRO1,N,N
102810,2013,780003000025,78,7800030,25,001,21,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,GLADYS A. ABRAHAM ELEMENTARY SCHOOL,3407747385,...,0,0,3,1,2,479,N,NSLPPRO1,N,N
102811,2013,780003000026,78,7800030,26,001,17,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,ULLA F MULLER ELEMENTARY SCHOOL,3407740059,...,0,0,7,1,6,484,N,NSLPPRO1,N,N
102812,2013,780003000027,78,7800030,27,001,23,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,YVONNE BOWSKY ELEMENTARY SCHOOL,3407753220,...,0,1,4,3,1,469,N,NSLPPRO1,N,N
102813,2013,780003000033,78,7800030,33,001,25,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,CANCRYN JUNIOR HIGH SCHOOL,3407744540,...,1,0,6,2,4,605,N,NSLPPRO1,N,N
102814,2013,780003000034,78,7800030,34,001,9,SAINT THOMAS - SAINT JOHN SCHOOL DISTRICT,BERTHA BOSCHULTE JUNIOR HIGH,3407754222,...,1,0,0,0,0,582,N,NSLPPRO1,N,N

In [ ]:
data_schinfo.shape

In [66]:
data_pov_cols = data_pov.columns
data_pov = data_pov[data_pov_cols[4:]]

In [67]:
rows = data_fisc['LEAID'].str.startswith('0')

strs = data_fisc['LEAID'][rows].str[1:]

data_fisc2 = data_fisc.copy()

data_fisc2['LEAID'][rows] = strs

data_fisc2['LEAID'] = data_fisc2['LEAID'].astype(str)

D:\Programs\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [68]:
data_fisc3 = data_fisc2.copy()

print(data_fisc3.shape)

data_fisc3['LEAID'] = data_fisc3['LEAID'].apply(pd.to_numeric, errors='coerce')

print(data_fisc3.shape)

data_fisc3 = data_fisc3[~(data_fisc3['LEAID'].isnull().values)]

print(data_fisc3.shape)

# data_fisc3['LEAID'] = data_fisc2['LEAID'].astype(str).str.replace('\d+', '')

print(data_fisc3.shape)

# data_fisc3 = data_fisc3[~(data_fisc3['LEAID'] == '')]
data_fisc3['LEAID'] = data_fisc3['LEAID'].astype(np.int64)

print(data_fisc3.shape)

(14397, 239)
(14397, 239)
(14377, 239)
(14377, 239)
(14377, 239)

In [69]:
fisc_cols = data_fisc3.columns

fisc_cols = fisc_cols[125:]

data_fisc4 = data_fisc3.drop(fisc_cols, axis=1)

fisc_cols

Index(['FL_V33', 'FL_MEMBERSCH', 'FL_C14', 'FL_C15', 'FL_C16', 'FL_C17',
       'FL_C19', 'FL_B11', 'FL_C20', 'FL_C25',
       ...
       'FL_31F', 'FL_41F', 'FL_61V', 'FL_66V', 'FL_W01', 'FL_W31', 'FL_W61',
       'FL_HR1', 'FL_HE1', 'FL_HE2'],
      dtype='object', length=114)

In [70]:
# data_schinfo['LEAID'] = data_schinfo['LEAID'].astype(int)
data_fisc4.shape

(14377, 125)

In [71]:
data_schinfo['LSTATE'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'MD', 'FL',
       'GA', 'HI', 'ID', 'OR', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME',
       'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM',
       'NY', 'NC', 'ND', 'OH', 'PA', 'OK', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'AS', 'AE', 'AP', 'PR',
       'GU', 'MP', 'VI'], dtype=object)

In [72]:
data_schinfo[data_schinfo['LSTATE'] == 'MT']

,SURVYEAR,NCESSCH,FIPST,LEAID,SCHNO,STID,SEASCH,LEANM,SCHNAM,PHONE,...,HPALM,HPALF,TR,TRALM,TRALF,TOTETH,VIRTUALSTAT,NSLPSTATUS,CHARTAUTH1,CHARTAUTH2
53301,2013,300000200705,30,3000002,705,0327,0439,SOMERS ELEM,LAKESIDE ELEMENTARY SCHOOL,4068442208,...,1,0,0,0,0,383,VIRTUALNO,NSLPWOPRO,N,N
53302,2013,300000200965,30,3000002,965,0327,1799,SOMERS ELEM,SOMERS MIDDLE SCHOOL,4068573661,...,0,1,0,0,0,186,VIRTUALNO,NSLPWOPRO,N,N
53303,2013,300000300018,30,3000003,18,0402,1810,CUT BANK ELEM,GLACIER ELEMENTARY SCHOOL,4063362623,...,0,0,0,0,0,16,VIRTUALNO,NSLPWOPRO,N,N
53304,2013,300000300233,30,3000003,233,0402,0545,CUT BANK ELEM,ANNA JEFFRIES ELEMENTARY,4068732411,...,0,0,14,10,4,93,VIRTUALNO,NSLPWOPRO,N,N
53305,2013,300000300234,30,3000003,234,0402,0544,CUT BANK ELEM,CUT BANK MIDDLE SCHOOL,4068734421,...,0,0,22,13,9,153,VIRTUALNO,NSLPWOPRO,N,N
53306,2013,300000300242,30,3000003,242,0402,1826,CUT BANK ELEM,HIDDEN LAKE ELEMENTARY,4063363696,...,0,0,0,0,0,2,VIRTUALNO,NSLPNO,N,N
53307,2013,300000301104,30,3000003,1104,0402,1842,CUT BANK ELEM,ZENITH ELEMENTARY,4063365430,...,0,0,0,0,0,15,VIRTUALNO,NSLPWOPRO,N,N
53308,2013,300000301106,30,3000003,1106,0402,0546,CUT BANK ELEM,H C DAVIS ELEMENTARY,4068735513,...,0,0,24,14,10,252,VIRTUALNO,NSLPWOPRO,N,N
53309,2013,300000301107,30,3000003,1107,0402,1844,CUT BANK ELEM,HORIZON ELEMENTARY,4063362961,...,0,0,0,0,0,12,VIRTUALNO,NSLPWOPRO,N,N
53310,2013,300000400899,30,3000004,899,1222,1621,MOUNTAIN VIEW ELEM,MOUNTAIN VIEW ELEMENTARY,4063362433,...,0,0,0,0,0,20,VIRTUALNO,NSLPNO,N,N
53311,2013,300000500337,30,3000005,337,0487,0662,HELENA ELEM,KESSLER ELEMENTARY SCHOOL,4063241700,...,0,0,4,2,2,254,VIRTUALNO,NSLPWOPRO,N,N
53312,2013,300000500415,30,3000005,415,0487,0655,HELENA ELEM,BROADWATER SCHOOL,4063241130,...,0,1,10,3,7,281,VIRTUALNO,NSLPWOPRO,N,N
53313,2013,300000500416,30,3000005,416,0487,0657,HELENA ELEM,BRYANT SCHOOL,4063241200,...,0,1,8,3,5,222,VIRTUALNO,NSLPWOPRO,N,N
53314,2013,300000500418,30,3000005,418,0487,0654,HELENA ELEM,CENTRAL SCHOOL,4063241230,...,2,0,5,2,3,247,VIRTUALNO,NSLPWOPRO,N,N
53315,2013,300000500419,30,3000005,419,0487,1582,HELENA ELEM,FOUR GEORGIANS SCHOOL,4063241300,...,3,0,6,1,5,495,VIRTUALNO,NSLPWOPRO,N,N
53316,2013,300000500420,30,3000005,420,0487,0656,HELENA ELEM,HAWTHORNE SCHOOL,4063241370,...,0,0,5,3,2,259,VIRTUALNO,NSLPWOPRO,N,N
53317,2013,300000500421,30,3000005,421,0487,0651,HELENA ELEM,JEFFERSON SCHOOL,4063242060,...,0,0,1,0,1,257,VIRTUALNO,NSLPWOPRO,N,N
53318,2013,300000500424,30,3000005,424,0487,1478,HELENA ELEM,ROSSITER SCHOOL,4063241500,...,1,0,4,3,1,480,VIRTUALNO,NSLPWOPRO,N,N
53319,2013,300000500425,30,3000005,425,0487,1477,HELENA ELEM,SMITH SCHOOL,4063241530,...,1,0,3,0,3,304,VIRTUALNO,NSLPWOPRO,N,N
53320,2013,300000500505,30,3000005,505,0487,1461,HELENA ELEM,JIM DARCY SCHOOL,4063241410,...,0,0,5,2,3,335,VIRTUALNO,NSLPWOPRO,N,N
53321,2013,300000500506,30,3000005,506,0487,0663,HELENA ELEM,WARREN SCHOOL,4063241600,...,0,0,6,4,2,330,VIRTUALNO,NSLPWOPRO,N,N
53322,2013,300000500885,30,3000005,885,0487,1614,HELENA ELEM,HELENA MIDDLE SCHOOL,4063241000,...,1,1,1,0,1,654,VIRTUALNO,NSLPWOPRO,N,N
53323,2013,300000500886,30,3000005,886,0487,1615,HELENA ELEM,C R ANDERSON MIDDLE SCHL,4063242800,...,3,0,5,2,3,1031,VIRTUALNO,NSLPWOPRO,N,N
53324,2013,300000600120,30,3000006,120,0705,0930,BROADUS ELEM,BROADUS SCHOOL,4064362637,...,0,0,7,1,6,94,VIRTUALNO,NSLPWOPRO,N,N
53325,2013,300000601035,30,3000006,1035,0705,1751,BROADUS ELEM,BROADUS 7-8,4064362658,...,0,0,4,2,2,43,VIRTUALNO,NSLPWOPRO,N,N
53326,2013,300000700707,30,3000007,707,0709,0934,SOUTH STACEY ELEM,SOUTH STACEY SCHOOL,4067842256,...,0,0,0,0,0,1,VIRTUALNO,NSLPNO,N,N
53327,2013,300000800023,30,3000008,23,0800,1043,ASHLAND ELEM,ASHLAND SCHOOL,4067842568,...,0,0,3,1,2,62,VIRTUALNO,NSLPWOPRO,N,N
53328,2013,300000801051,30,3000008,1051,0800,1763,ASHLAND ELEM,ASHLAND 7-8,4067842568,...,0,0,1,0,1,14,VIRTUALNO,NSLPWOPRO,N,N
53329,2013,300008900875,30,3000089,875,0182,0253,COTTONWOOD ELEM,KNOWLTON SCHOOL,4067725888,...,-2,-2,-2,-2,-2,-2,VIRTUALNO,M,N,N
53330,2013,300009000599,30,3000090,599,0811,1054,NOXON ELEM,NOXON SCHOOL,4068472442,...,0,0,5,4,1,81,VIRTUALNO,NSLPWOPRO,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54108,2013,302814000785,30,3028140,785,0354,0476,WILLOW CREEK ELEM,WILLOW CREEK SCHOOL,4062856991,...,0,0,0,0,0,31,VIRTUALNO,NSLPWOPRO,N,N
54109,2013,302814000972,30,3028140,972,0354,1700,WILLOW CREEK ELEM,WILLOW CREEK 7-8,4062856991,...,0,0,0,0,0,9,VIRTUALNO,NSLPWOPRO,N,N
54110,2013,302817000786,30,3028170,786,0355,0477,WILLOW CREEK H S,WILLOW CREEK HIGH SCHOOL,4062856991,...,0,0,0,0,0,15,VIRTUALNO,NSLPWOPRO,N,N
54111,2013,302838000789,30,3028380,789,0291,0391,WINIFRED K-12 SCHOOLS,WINIFRED SCHOOL,4064625349,...,0,0,0,0,0,48,VIRTUALNO,NSLPWOPRO,N,N
54112,2013,302838000790,30,3028380,790,0291,0392,WINIFRED K-12 SCHOOLS,WINIFRED HIGH SCHOOL,4064625420,...,0,0,0,0,0,31,VIRTUALNO,NSLPWOPRO,N,N
54113,2013,302838000959,30,3028380,959,0291,1691,WINIFRED K-12 SCHOOLS,WINIFRED 7-8,4064625349,...,0,0,0,0,0,18,VIRTUALNO,NSLPWOPRO,N,N
54114,2013,302847000791,30,3028470,791,0642,0852,WINNETT K-12 SCHOOLS,WINNETT SCHOOL,4064292251,...,0,0,0,0,0,34,VIRTUALNO,NSLPWOPRO,N,N
54115,2013,302847000792,30,3028470,792,0642,0853,WINNETT K-12 SCHOOLS,WINNETT HIGH SCHOOL,4064292251,...,0,0,0,0,0,37,VIRTUALNO,NSLPWOPRO,N,N
54116,2013,302847001027,30,3028470,1027,0642,1744,WINNETT K-12 SCHOOLS,WINNETT 7-8,4064292251,...,0,0,0,0,0,14,VIRTUALNO,NSLPWOPRO,N,N
54117,2013,302850000793,30,3028500,793,0010,0012,WISDOM ELEM,WISDOM SCHOOL,4066893227,...,0,0,0,0,0,16,VIRTUALNO,NSLPNO,N,N
54118,2013,302855000795,30,3028550,795,0495,0668,WOLF CREEK ELEM,WOLF CREEK SCHOOL,4062354241,...,0,0,0,0,0,6,VIRTUALNO,NSLPWOPRO,N,N
54119,2013,302859000796,30,3028590,796,0780,1022,WOLF POINT ELEM,NORTHSIDE SCHOOL,4066531653,...,0,0,29,12,17,188,VIRTUALNO,NSLPPRO2,N,N
54120,2013,302859000797,30,3028590,797,0780,1020,WOLF POINT ELEM,SOUTHSIDE SCHOOL,4066531480,...,0,0,52,21,31,307,VIRTUALNO,NSLPPRO2,N,N
54121,2013,302859000798,30,3028590,798,0780,1532,WOLF POINT ELEM,WOLF POINT 7-8,4066531200,...,0,0,20,9,11,135,VIRTUALNO,NSLPPRO2,N,N
54122,2013,302862000799,30,3028620,799,0781,1023,WOLF POINT H S,WOLF POINT HIGH SCHOOL,4066531200,...,0,0,38,21,17,220,VIRTUALNO,NSLPPRO2,N,N
54123,2013,302865000800,30,3028650,800,0591,0795,WOODMAN ELEM,WOODMAN SCHOOL,4062736770,...,0,0,0,0,0,31,VIRTUALNO,NSLPNO,N,N
54124,2013,302865001013,30,3028650,1013,0591,1735,WOODMAN ELEM,WOODMAN 7-8,4062736770,...,0,0,0,0,0,10,VIRTUALNO,NSLPNO,N,N
54125,2013,302875000802,30,3028750,802,0569,0758,WHITE SULPHUR SPGS ELEM,WHITE SULPHUR SPRINGS EL,4065473751,...,0,0,2,1,1,113,VIRTUALNO,NSLPWOPRO,N,N
54126,2013,302875001006,30,3028750,1006,0569,1729,WHITE SULPHUR SPGS ELEM,WHITE SULPHUR SPRINGS 7-8,4065473351,...,0,0,2,0,2,23,VIRTUALNO,NSLPWOPRO,N,N
54127,2013,302877000803,30,3028770,803,0570,0759,WHITE SULPHUR SPGS H S,WHITE SULPHUR SPRINGS HS,4065473351,...,0,0,0,0,0,61,VIRTUALNO,NSLPWOPRO,N,N
54128,2013,302880000355,30,3028800,355,0026,1583,WYOLA ELEM,WYOLA 7-8,4063432722,...,0,0,0,0,0,18,VIRTUALNO,NSLPPRO2,N,N
54129,2013,302880000804,30,3028800,804,0026,0041,WYOLA ELEM,WYOLA SCHOOL,4063432722,...,0,0,0,0,0,101,VIRTUALNO,NSLPWOPRO,N,N
54130,2013,302883000805,30,3028830,805,0533,0716,YAAK ELEM,YAAK SCHOOL,4062954805,...,0,0,0,0,0,5,VIRTUALNO,NSLPNO,N,N
54131,2013,302886000806,30,3028860,806,1196,1456,YELLOWSTONE ACADEMY ELEM,YELLOWSTONE ACADEMY ELEM,4066562198,...,0,0,1,1,0,33,VIRTUALNO,NSLPWOPRO,N,N
54132,2013,302891000807,30,3028910,807,0034,0056,ZURICH ELEM,ZURICH SCHOOL,4063574164,...,0,0,2,0,2,22,VIRTUALNO,NSLPWOPRO,N,N
54133,2013,302891101086,30,3028911,1086,1229,1807,ROCKY BOY H S,ROCKY BOY HIGH SCHOOL,4063954270,...,0,0,0,0,0,137,VIRTUALNO,NSLPPRO2,N,N
67666,2013,380567000826,38,3805670,826,27018,81061,EARL 18,SQUAW GAP SCHOOL,7015652230,...,0,0,0,0,0,0,N,NSLPWOPRO,N,N
67965,2013,382034000714,38,3820340,714,27014,27411,YELLOWSTONE 14,EAST FAIRVIEW ELEMENTARY SCHOOL,7018445649,...,0,0,4,2,2,80,N,NSLPWOPRO,N,N
100874,2013,590004100002,59,5900041,2,D57C04,D57C04,NORTHERN CHEYENNE TRIBAL SCHOOL,NORTHERN CHEYENNE TRIBAL SCHOOL,4065923646,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N
101011,2013,590017800129,59,5900178,129,D13P02,D13P02,TWO EAGLE RIVER SCHOOL,TWO EAGLE RIVER SCHOOL,4066750292,...,-1,-1,-1,-1,-1,-1,VIRTUALNO,M,N,N

In [73]:
data_merged = data_schinfo.merge(data_reading, on='NCESSCH', how='inner')
data_merged = data_merged.merge(data_math, on='NCESSCH', how='inner')


data_merged[data_merged['LSTATE'] == 'MT']

,SURVYEAR,NCESSCH,FIPST,LEAID,SCHNO,STID,SEASCH,LEANM,SCHNAM,PHONE,...,TRALF,TOTETH,VIRTUALSTAT,NSLPSTATUS,CHARTAUTH1,CHARTAUTH2,ALL_RLA00NUMVALID_1314,ALL_RLA00PCTPROF_1314,ALL_MTH00NUMVALID_1314,ALL_MTH00PCTPROF_1314
34417,2013,300000500886,30,3000005,886,0487,1615,HELENA ELEM,C R ANDERSON MIDDLE SCHL,4063242800,...,3,1031,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34418,2013,300201000010,30,3002010,10,0236,0322,ANACONDA ELEM,LINCOLN SCHOOL,4065636361,...,0,247,VIRTUALNO,NSLPWOPRO,N,N,18,90.0,18,69.5
34419,2013,300201000014,30,3002010,14,0236,1589,ANACONDA ELEM,FRED MOODRY 7-8,4065636361,...,0,245,VIRTUALNO,NSLPWOPRO,N,N,9,75.0,9,75.0
34420,2013,300329000044,30,3003290,44,0368,1575,BELGRADE ELEM,BELGRADE MIDDLE SCHOOL,4069242259,...,5,913,VIRTUALNO,NSLPWOPRO,N,N,9,75.0,9,75.0
34421,2013,300387000073,30,3003870,73,0965,1439,BILLINGS ELEM,MEADOWLARK SCHOOL,4062816213,...,17,657,VIRTUALNO,NSLPWOPRO,N,N,15,25.0,15,25.0
34422,2013,300387000085,30,3003870,85,0965,1270,BILLINGS ELEM,WASHINGTON SCHOOL,4062816221,...,11,260,VIRTUALNO,NSLPWOPRO,N,N,16,90.0,16,90.0
34423,2013,300387000808,30,3003870,808,0965,1597,BILLINGS ELEM,ALKALI CREEK SCHOOL,4062816200,...,5,393,VIRTUALNO,NSLPWOPRO,N,N,9,75.0,9,75.0
34424,2013,300387000869,30,3003870,869,0965,1631,BILLINGS ELEM,CASTLE ROCK 7-8,4062815800,...,8,777,VIRTUALNO,NSLPWOPRO,N,N,9,75.0,9,75.0
34425,2013,300387000870,30,3003870,870,0965,1632,BILLINGS ELEM,LEWIS & CLARK MIDDLE SCHOOL,4062815900,...,10,697,VIRTUALNO,NSLPWOPRO,N,N,16,69.5,16,69.5
34426,2013,300387000902,30,3003870,902,0965,1639,BILLINGS ELEM,EAGLE CLIFFS ELEMENTARY,4062816210,...,11,450,VIRTUALNO,NSLPWOPRO,N,N,7,25.0,7,25.0
34427,2013,300456000017,30,3004560,17,0350,1813,BOZEMAN ELEM,EMILY DICKINSON SCHOOL,4065226650,...,0,466,VIRTUALNO,NSLPWOPRO,N,N,6,75.0,6,75.0
34428,2013,300456000112,30,3004560,112,0350,1463,BOZEMAN ELEM,CHIEF JOSEPH MIDDLE SCHOOL,4065226300,...,7,667,VIRTUALNO,NSLPWOPRO,N,N,7,75.0,7,75.0
34429,2013,300456001096,30,3004560,1096,0350,1839,BOZEMAN ELEM,HYALITE ELEMENTARY,4065826800,...,6,519,VIRTUALNO,NSLPWOPRO,N,N,6,75.0,6,75.0
34430,2013,300459000113,30,3004590,113,0351,0473,BOZEMAN H S,BOZEMAN HIGH SCHOOL,4065226200,...,11,1951,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34431,2013,300528000153,30,3005280,153,0840,1101,BUTTE ELEM,WHITTIER SCHOOL,4065332890,...,2,445,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,25.0
34432,2013,300528000905,30,3005280,905,0840,1641,BUTTE ELEM,EAST MIDDLE SCHOOL,4065332600,...,1,623,VIRTUALNO,NSLPWOPRO,N,N,7,75.0,7,75.0
34433,2013,300528000906,30,3005280,906,0840,1642,BUTTE ELEM,WEST ELEMENTARY SCHOOL,4065332700,...,4,562,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34434,2013,300711000195,30,3007110,195,0312,0419,COLUMBIA FALLS ELEM,COLUMBIA FALLS JR HS,4068926530,...,16,473,VIRTUALNO,NSLPWOPRO,N,N,9,75.0,9,75.0
34435,2013,301092000294,30,3010920,294,0339,1508,EVERGREEN ELEM,EVERGREEN 5-6 SCHOOL,4067511131,...,0,184,VIRTUALNO,NSLPWOPRO,N,N,6,75.0,6,75.0
34436,2013,301152001105,30,3011520,1105,0599,1845,FRENCHTOWN K-12 SCHOOLS,FRENCHTOWN INTERMEDIATE SCHOOL,4066262622,...,0,178,VIRTUALNO,NSLPWOPRO,N,N,6,75.0,6,25.0
34437,2013,301304000881,30,3013040,881,0098,1624,GREAT FALLS ELEM,WEST ELEMENTARY,4062687180,...,3,486,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34438,2013,301305000379,30,3013050,379,0099,1464,GREAT FALLS H S,C M RUSSELL HIGH SCHOOL,4062686100,...,10,1515,VIRTUALNO,NSLPWOPRO,N,N,6,75.0,6,75.0
34439,2013,301356000406,30,3013560,406,0427,1451,HAVRE ELEM,HAVRE MIDDLE SCHOOL,4062659613,...,12,471,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34440,2013,301386000432,30,3013860,432,0586,1573,HELLGATE ELEM,LOWER GRADE HELLGATE,4067212160,...,30,986,VIRTUALNO,NSLPWOPRO,N,N,7,75.0,7,75.0
34441,2013,301545000086,30,3015450,86,0310,1509,KALISPELL ELEM,KALISPELL MIDDLE SCHOOL,4067513800,...,1,1054,VIRTUALNO,NSLPWOPRO,N,N,14,75.0,14,75.0
34442,2013,301545000471,30,3015450,471,0310,0415,KALISPELL ELEM,CORNELIUS HEDGES SCHOOL,4067514090,...,1,386,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34443,2013,301605000494,30,3016050,494,0792,1035,LAME DEER ELEM,LAME DEER SCHOOL,4064776305,...,4,334,VIRTUALNO,NSLPPRO2,N,N,7,75.0,7,75.0
34444,2013,301688000524,30,3016880,524,0612,0817,LIVINGSTON ELEM,EAST SIDE SCHOOL,4062221773,...,3,285,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34445,2013,301695000912,30,3016950,912,0967,1647,LOCKWOOD ELEM,LOCKWOOD MIDDLE SCHOOL,4062590154,...,1,405,VIRTUALNO,NSLPWOPRO,N,N,6,75.0,6,25.0
34446,2013,301854000824,30,3018540,824,0584,1592,MISSOULA H S,BIG SKY HIGH SCHOOL,4067282401,...,9,1060,VIRTUALNO,NSLPWOPRO,N,N,6,75.0,6,75.0
34447,2013,301857000570,30,3018570,570,0583,0787,MISSOULA ELEM,HAWTHORNE SCHOOL,4065424025,...,1,380,VIRTUALNO,NSLPWOPRO,N,N,7,75.0,7,75.0
34448,2013,301857000575,30,3018570,575,0583,1491,MISSOULA ELEM,MEADOW HILL MIDDLE SCHOOL,4065424045,...,0,480,VIRTUALNO,NSLPWOPRO,N,N,7,75.0,7,75.0
34449,2013,301857000580,30,3018570,580,0583,0778,MISSOULA ELEM,RUSSELL SCHOOL,4065424080,...,1,373,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34450,2013,302106000632,30,3021060,632,0477,1498,POLSON ELEM,POLSON 7-8,4068836335,...,0,250,VIRTUALNO,NSLPWOPRO,N,N,8,75.0,8,75.0
34451,2013,302279000668,30,3022790,668,1199,1519,RONAN ELEM,RONAN MIDDLE SCHOOL,4066763390,...,2,438,VIRTUALNO,NSLPWOPRO,N,N,10,75.0,10,75.0
46877,2013,382034000714,38,3820340,714,27014,27411,YELLOWSTONE 14,EAST FAIRVIEW ELEMENTARY SCHOOL,7018445649,...,2,80,N,NSLPWOPRO,N,N,43,84.5,43,84.5

In [74]:
data_merged['LEAID'] = data_merged['LEAID'].astype(np.int64)
data_merged = data_merged.merge(data_pov, on='LEAID', how='inner')
data_merged = data_merged.merge(data_fisc4, on='LEAID', how='inner')
data_merged = data_merged.merge(data_district2, on='LEAID', how='inner')

data_merged['avg_teacher_salary'] = data_merged['Z35'] / data_merged['TOTTCH']

In [75]:
data_cols = data_merged.columns
data_merged.shape

(68931, 446)

In [76]:
data_merged[data_merged['LSTATE'] == 'MT']

,SURVYEAR,NCESSCH,FIPST,LEAID,SCHNO,STID,SEASCH,LEANM,SCHNAM,PHONE,...,_66V,W01,W31,W61,HR1,HE1,HE2,WEIGHT,TOTTCH,avg_teacher_salary
32431,2013,300000500886,30,3000005,886,0487,1615,HELENA ELEM,C R ANDERSON MIDDLE SCHL,4063242800,...,0,105000,962000,5885000,0,0,0,1,298.34,0.0
32432,2013,300201000010,30,3002010,10,0236,0322,ANACONDA ELEM,LINCOLN SCHOOL,4065636361,...,0,0,291000,2710000,0,0,0,1,49.38,0.0
32433,2013,300201000014,30,3002010,14,0236,1589,ANACONDA ELEM,FRED MOODRY 7-8,4065636361,...,0,0,291000,2710000,0,0,0,1,49.38,0.0
32434,2013,300329000044,30,3003290,44,0368,1575,BELGRADE ELEM,BELGRADE MIDDLE SCHOOL,4069242259,...,0,770000,946000,5685000,0,0,0,1,133.15,0.0
32435,2013,300387000073,30,3003870,73,0965,1439,BILLINGS ELEM,MEADOWLARK SCHOOL,4062816213,...,0,2448000,89076000,14309000,0,0,0,1,677.76,0.0
32436,2013,300387000085,30,3003870,85,0965,1270,BILLINGS ELEM,WASHINGTON SCHOOL,4062816221,...,0,2448000,89076000,14309000,0,0,0,1,677.76,0.0
32437,2013,300387000808,30,3003870,808,0965,1597,BILLINGS ELEM,ALKALI CREEK SCHOOL,4062816200,...,0,2448000,89076000,14309000,0,0,0,1,677.76,0.0
32438,2013,300387000869,30,3003870,869,0965,1631,BILLINGS ELEM,CASTLE ROCK 7-8,4062815800,...,0,2448000,89076000,14309000,0,0,0,1,677.76,0.0
32439,2013,300387000870,30,3003870,870,0965,1632,BILLINGS ELEM,LEWIS & CLARK MIDDLE SCHOOL,4062815900,...,0,2448000,89076000,14309000,0,0,0,1,677.76,0.0
32440,2013,300387000902,30,3003870,902,0965,1639,BILLINGS ELEM,EAGLE CLIFFS ELEMENTARY,4062816210,...,0,2448000,89076000,14309000,0,0,0,1,677.76,0.0
32441,2013,300456000017,30,3004560,17,0350,1813,BOZEMAN ELEM,EMILY DICKINSON SCHOOL,4065226650,...,0,16000,6723000,6488000,0,0,0,1,264.12,0.0
32442,2013,300456000112,30,3004560,112,0350,1463,BOZEMAN ELEM,CHIEF JOSEPH MIDDLE SCHOOL,4065226300,...,0,16000,6723000,6488000,0,0,0,1,264.12,0.0
32443,2013,300456001096,30,3004560,1096,0350,1839,BOZEMAN ELEM,HYALITE ELEMENTARY,4065826800,...,0,16000,6723000,6488000,0,0,0,1,264.12,0.0
32444,2013,300459000113,30,3004590,113,0351,0473,BOZEMAN H S,BOZEMAN HIGH SCHOOL,4065226200,...,0,15000,2084000,6486000,0,0,0,1,117.50,0.0
32445,2013,300528000153,30,3005280,153,0840,1101,BUTTE ELEM,WHITTIER SCHOOL,4065332890,...,0,74000,2828000,14410000,0,0,0,1,180.94,0.0
32446,2013,300528000905,30,3005280,905,0840,1641,BUTTE ELEM,EAST MIDDLE SCHOOL,4065332600,...,0,74000,2828000,14410000,0,0,0,1,180.94,0.0
32447,2013,300528000906,30,3005280,906,0840,1642,BUTTE ELEM,WEST ELEMENTARY SCHOOL,4065332700,...,0,74000,2828000,14410000,0,0,0,1,180.94,0.0
32448,2013,300711000195,30,3007110,195,0312,0419,COLUMBIA FALLS ELEM,COLUMBIA FALLS JR HS,4068926530,...,0,189000,564000,2774000,0,0,0,1,93.57,0.0
32449,2013,301092000294,30,3010920,294,0339,1508,EVERGREEN ELEM,EVERGREEN 5-6 SCHOOL,4067511131,...,0,150000,632000,2688000,0,0,0,1,46.73,0.0
32450,2013,301152001105,30,3011520,1105,0599,1845,FRENCHTOWN K-12 SCHOOLS,FRENCHTOWN INTERMEDIATE SCHOOL,4066262622,...,0,205000,14000,2360000,0,0,0,1,77.33,0.0
32451,2013,301304000881,30,3013040,881,0098,1624,GREAT FALLS ELEM,WEST ELEMENTARY,4062687180,...,0,0,1120000,26815000,0,0,0,1,474.02,0.0
32452,2013,301305000379,30,3013050,379,0099,1464,GREAT FALLS H S,C M RUSSELL HIGH SCHOOL,4062686100,...,0,1000,148000,13070000,0,0,0,1,204.15,0.0
32453,2013,301356000406,30,3013560,406,0427,1451,HAVRE ELEM,HAVRE MIDDLE SCHOOL,4062659613,...,0,0,5700000,2118000,0,0,0,1,84.36,0.0
32454,2013,301386000432,30,3013860,432,0586,1573,HELLGATE ELEM,LOWER GRADE HELLGATE,4067212160,...,0,563000,396000,2523000,0,0,0,1,78.00,0.0
32455,2013,301545000086,30,3015450,86,0310,1509,KALISPELL ELEM,KALISPELL MIDDLE SCHOOL,4067513800,...,0,389000,1642000,3986000,0,0,0,1,185.20,0.0
32456,2013,301545000471,30,3015450,471,0310,0415,KALISPELL ELEM,CORNELIUS HEDGES SCHOOL,4067514090,...,0,389000,1642000,3986000,0,0,0,1,185.20,0.0
32457,2013,301605000494,30,3016050,494,0792,1035,LAME DEER ELEM,LAME DEER SCHOOL,4064776305,...,0,0,265000,3481000,0,0,0,1,28.83,0.0
32458,2013,301688000524,30,3016880,524,0612,0817,LIVINGSTON ELEM,EAST SIDE SCHOOL,4062221773,...,0,95000,81000,1227000,0,0,0,1,62.04,0.0
32459,2013,301695000912,30,3016950,912,0967,1647,LOCKWOOD ELEM,LOCKWOOD MIDDLE SCHOOL,4062590154,...,0,143000,436000,3028000,0,0,0,1,76.00,0.0
32460,2013,301854000824,30,3018540,824,0584,1592,MISSOULA H S,BIG SKY HIGH SCHOOL,4067282401,...,0,496000,967000,4570000,0,0,0,1,238.87,0.0
32461,2013,301857000570,30,3018570,570,0583,0787,MISSOULA ELEM,HAWTHORNE SCHOOL,4065424025,...,0,131000,2294000,4805000,0,0,0,1,320.45,0.0
32462,2013,301857000575,30,3018570,575,0583,1491,MISSOULA ELEM,MEADOW HILL MIDDLE SCHOOL,4065424045,...,0,131000,2294000,4805000,0,0,0,1,320.45,0.0
32463,2013,301857000580,30,3018570,580,0583,0778,MISSOULA ELEM,RUSSELL SCHOOL,4065424080,...,0,131000,2294000,4805000,0,0,0,1,320.45,0.0
32464,2013,302106000632,30,3021060,632,0477,1498,POLSON ELEM,POLSON 7-8,4068836335,...,0,0,0,2156000,0,0,0,1,82.94,0.0
32465,2013,302279000668,30,3022790,668,1199,1519,RONAN ELEM,RONAN MIDDLE SCHOOL,4066763390,...,0,262000,0,4617000,0,0,0,1,68.18,0.0
42798,2013,382034000714,38,3820340,714,27014,27411,YELLOWSTONE 14,EAST FAIRVIEW ELEMENTARY SCHOOL,7018445649,...,0,0,0,443000,0,0,0,1,10.00,43900.0

In [77]:
ulocal = data_merged['ULOCAL'].unique()

print(data_merged['ULOCAL'])

0        32
1        32
2        32
3        32
4        42
5        42
6        41
7        42
8        42
9        41
10       42
11       41
12       41
13       42
14       42
15       42
16       13
17       13
18       13
19       13
20       13
21       41
22       13
23       13
24       13
25       13
26       13
27       13
28       13
29       13
         ..
68901    33
68902    33
68903    33
68904    43
68905    43
68906    43
68907    33
68908    33
68909    33
68910    33
68911    33
68912    33
68913    33
68914    33
68915    43
68916    33
68917    41
68918    33
68919    43
68920    43
68921    42
68922    41
68923    43
68924    43
68925    43
68926    33
68927    33
68928    33
68929    33
68930    33
Name: ULOCAL, Length: 68931, dtype: object

In [78]:
data_merged2 = data_merged.copy()
data_merged2['ULOCAL'] = data_merged2['ULOCAL'].astype(int)

ulocal = data_merged2['ULOCAL'].unique()
data_merged2['ULOCAL'] = data_merged2['ULOCAL'].astype("category", ordered=True, categories=ulocal).cat.codes

# ulocal = pd.get_dummies(data_merged2['ULOCAL'])
# names = ['City, Large', 'City, Mid-size', 'City, Small', 'Suburb, Large', 'Suburb, Mid-Size', 
#         'Suburb, Small', 'Town, Fringe', 'Town, Distant', 'Town, Remote', 'Rural, Fringe', 'Rural, Distant', 
#         'Rural, Remote']

# ulocal.columns = names

# data_merged2[names] = ulocal
# data_merged2 = data_merged2.drop(['ULOCAL'], axis=1)

In [79]:
data_merged2['ULOCAL']

0        0
1        0
2        0
3        0
4        1
5        1
6        2
7        1
8        1
9        2
10       1
11       2
12       2
13       1
14       1
15       1
16       3
17       3
18       3
19       3
20       3
21       2
22       3
23       3
24       3
25       3
26       3
27       3
28       3
29       3
        ..
68901    5
68902    5
68903    5
68904    8
68905    8
68906    8
68907    5
68908    5
68909    5
68910    5
68911    5
68912    5
68913    5
68914    5
68915    8
68916    5
68917    2
68918    5
68919    8
68920    8
68921    1
68922    2
68923    8
68924    8
68925    8
68926    5
68927    5
68928    5
68929    5
68930    5
Name: ULOCAL, Length: 68931, dtype: int8

In [80]:
data_merged3 = data_merged2.copy()
data_merged3.loc[data_merged3['GSLO'] == 'N', ('GSLO')] = -3
data_merged3.loc[data_merged3['GSLO'] == 'UG', ('GSLO')] = -2
data_merged3.loc[data_merged3['GSLO'] == 'PK', ('GSLO')] = -1
data_merged3.loc[data_merged3['GSLO'] == 'KG', ('GSLO')] = 0

data_merged3.loc[data_merged3['GSHI'] == 'N', ('GSLO')] = -3
data_merged3.loc[data_merged3['GSHI'] == 'UG', ('GSLO')] = -2
data_merged3.loc[data_merged3['GSHI'] == 'PK', ('GSLO')] = -1
data_merged3.loc[data_merged3['GSHI'] == 'KG', ('GSLO')] = 0


data_merged3 = data_merged3.drop(data_merged3['GSLO'] == -2)

ungrade = ((data_merged3['GSLO'] == -2) | (data_merged3['GSLO'] == -3)
 | (data_merged3['GSHI'] == -2) | (data_merged3['GSHI'] == -3))

data_merged3 = data_merged3[~ungrade]

In [81]:
data_final = data_merged3

In [82]:
data_final.to_csv('data/final_data/data_final.csv', index=False, encoding='utf-8')

In [83]:
data_test_final = pd.read_csv('data/final_data/data_final.csv')
data_test_final

D:\Programs\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (5,6,9,34,51,52,54,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,SURVYEAR,NCESSCH,FIPST,LEAID,SCHNO,STID,SEASCH,LEANM,SCHNAM,PHONE,...,_66V,W01,W31,W61,HR1,HE1,HE2,WEIGHT,TOTTCH,avg_teacher_salary
0,2013,10000500879,1,100005,879,101,110,ALBERTVILLE CITY,EVANS ELEM SCH,2568787698,...,0,1193000,6196000,3481000,0,0,0,1,259.50,40589.595376
1,2013,10000500889,1,100005,889,101,200,ALBERTVILLE CITY,ALBERTVILLE ELEM SCH,2568786611,...,0,1193000,6196000,3481000,0,0,0,1,259.50,40589.595376
2,2013,10000600193,1,100006,193,48,143,MARSHALL COUNTY,KATE DUNCAN SMITH DAR MIDDLE,2567285950,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
3,2013,10000600872,1,100006,872,48,30,MARSHALL COUNTY,ASBURY SCH,2568784068,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
4,2013,10000600876,1,100006,876,48,70,MARSHALL COUNTY,CLAYSVILLE JR HIGH SCH,2565824444,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
5,2013,10000600877,1,100006,877,48,90,MARSHALL COUNTY,DOUGLAS ELEM SCH,2565934420,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
6,2013,10000600878,1,100006,878,48,100,MARSHALL COUNTY,DOUGLAS HIGH SCH,2565932810,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
7,2013,10000600880,1,100006,880,48,120,MARSHALL COUNTY,GRASSY ELEM SCH,2567532246,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
8,2013,10000600883,1,100006,883,48,140,MARSHALL COUNTY,KATE D SMITH DAR HIGH SCH,2567284238,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
9,2013,10000601434,1,100006,1434,48,40,MARSHALL COUNTY,BRINDLEE MT MIDDLE SCH,2567532820,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
10,2013,10000601585,1,100006,1585,48,42,MARSHALL COUNTY,BRINDLEE MT HIGH SCH,2567532800,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
11,2013,10000601685,1,100006,1685,48,145,MARSHALL COUNTY,KATE D SMITH DAR ELEM SCH,2567282226,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
12,2013,10000601812,1,100006,1812,48,105,MARSHALL COUNTY,DOUGLAS MIDDLE SCH,2565931240,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
13,2013,10000602209,1,100006,2209,48,35,MARSHALL COUNTY,ASBURY ELEMENTARY SCHOOL,2568786221,...,0,1334000,2590000,6856000,84000,84000,0,1,359.20,34910.913140
14,2013,10000700091,1,100007,91,158,820,HOOVER CITY,TRACE CROSSINGS ELEM SCH,2054392700,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
15,2013,10000700248,1,100007,248,158,360,HOOVER CITY,GREYSTONE ELEM SCH,2054393200,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
16,2013,10000700251,1,100007,251,158,400,HOOVER CITY,HOOVER HIGH SCH,2054391200,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
17,2013,10000700337,1,100007,337,158,70,HOOVER CITY,BERRY MIDDLE SCH,2054392000,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
18,2013,10000700342,1,100007,342,158,815,HOOVER CITY,SOUTH SHADES CREST ELEM SCH,2054393000,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
19,2013,10000701422,1,100007,1422,158,415,HOOVER CITY,ROBERT F BUMPUS MIDDLE SCH,2054392200,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
20,2013,10000701456,1,100007,1456,158,10,HOOVER CITY,SPAIN PARK HIGH SCH,2054391400,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
21,2013,10000701483,1,100007,1483,158,380,HOOVER CITY,DEER VALLEY ELEM SCH,2054393300,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
22,2013,10000701738,1,100007,1738,158,80,HOOVER CITY,BLUFF PK ELEM SCH,2054392800,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
23,2013,10000701739,1,100007,1739,158,350,HOOVER CITY,GREEN VALLEY ELEM SCH,2054392500,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
24,2013,10000701740,1,100007,1740,158,365,HOOVER CITY,GWIN ELEM SCH,2054392600,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
25,2013,10000701741,1,100007,1741,158,425,HOOVER CITY,IRA F SIMMONS MIDDLE SCH,2054392100,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
26,2013,10000701742,1,100007,1742,158,760,HOOVER CITY,ROCKY RIDGE ELEM SCH,2054392900,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
27,2013,10000701743,1,100007,1743,158,810,HOOVER CITY,SHADES MT ELEM SCH,2054393100,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
28,2013,10000702091,1,100007,2091,158,410,HOOVER CITY,RIVERCHASE ELEM SCH,2054393400,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
29,2013,10000702186,1,100007,2186,158,420,HOOVER CITY,BROCK'S GAP INTERMEDIATE SCH,2052311740,...,0,18223000,3596000,86590000,0,0,0,1,938.13,52486.329187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68872,2013,560569500361,56,5605695,361,1702000,1702050,SHERIDAN COUNTY SCHOOL DISTRICT #2,SHERIDAN JUNIOR HIGH SCHOOL,3076729745,...,0,0,0,12941000,0,0,0,1,256.56,55285.313377
68873,2013,560569500397,56,5605695,397,1702000,1702009,SHERIDAN COUNTY SCHOOL DISTRICT #2,MEADOWLARK ELEMENTARY,3076723786,...,0,0,0,12941000,0,0,0,1,256.56,55285.313377
68874,2013,560569500474,56,5605695,474,1702000,1702010,SHERIDAN COUNTY SCHOOL DISTRICT #2,SAGEBRUSH ELEMENTARY,3076729059,...,0,0,0,12941000,0,0,0,1,256.56,55285.313377
68875,2013,560570000323,56,5605700,323,724000,724055,FREMONT COUNTY SCHOOL DISTRICT #24,SHOSHONI HIGH SCHOOL,3078762576,...,0,0,0,4106000,0,0,0,1,30.32,46174.142480
68876,2013,560570000362,56,5605700,362,724000,724001,FREMONT COUNTY SCHOOL DISTRICT #24,SHOSHONI ELEMENTARY,3078762563,...,0,0,0,4106000,0,0,0,1,30.32,46174.142480
68877,2013,560570000510,56,5605700,510,724000,724050,FREMONT COUNTY SCHOOL DISTRICT #24,SHOSHONI JUNIOR HIGH SCHOOL,3078762576,...,0,0,0,4106000,0,0,0,1,30.32,46174.142480
68878,2013,560576200164,56,5605762,164,1902000,1902056,SWEETWATER COUNTY SCHOOL DISTRICT #2,EXPEDITION ACADEMY,3078724800,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68879,2013,560576200285,56,5605762,285,1902000,1902012,SWEETWATER COUNTY SCHOOL DISTRICT #2,MONROE INTERMEDIATE SCHOOL,3078724000,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68880,2013,560576200324,56,5605762,324,1902000,1902055,SWEETWATER COUNTY SCHOOL DISTRICT #2,GREEN RIVER HIGH SCHOOL,3078724747,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68881,2013,560576200332,56,5605762,332,1902000,1902007,SWEETWATER COUNTY SCHOOL DISTRICT #2,WASHINGTON ELEMENTARY,3078722000,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68882,2013,560576200399,56,5605762,399,1902000,1902050,SWEETWATER COUNTY SCHOOL DISTRICT #2,LINCOLN MIDDLE SCHOOL,3078724400,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68883,2013,560576200424,56,5605762,424,1902000,1902010,SWEETWATER COUNTY SCHOOL DISTRICT #2,JACKSON ELEMENTARY,3078721800,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68884,2013,560576200425,56,5605762,425,1902000,1902011,SWEETWATER COUNTY SCHOOL DISTRICT #2,TRUMAN ELEMENTARY,3078721900,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68885,2013,560576200439,56,5605762,439,1902000,1902002,SWEETWATER COUNTY SCHOOL DISTRICT #2,HARRISON ELEMENTARY,3078721700,...,0,157000,0,15300000,0,0,0,1,225.50,44368.070953
68886,2013,560582000393,56,5605820,393,2202000,2202049,WASHAKIE COUNTY SCHOOL DISTRICT #2,TEN SLEEP K-12,3073662233,...,0,7000,0,1467000,0,0,0,1,13.50,63037.037037
68887,2013,560583000289,56,5605830,289,2001000,2001009,TETON COUNTY SCHOOL DISTRICT #1,COLTER ELEMENTARY,3077339651,...,0,0,0,12962000,286000,84000,0,1,215.53,60464.900478
68888,2013,560583000335,56,5605830,335,2001000,2001055,TETON COUNTY SCHOOL DISTRICT #1,JACKSON HOLE HIGH SCHOOL,3077323700,...,0,0,0,12962000,286000,84000,0,1,215.53,60464.900478
68889,2013,560583000336,56,5605830,336,2001000,2001050,TETON COUNTY SCHOOL DISTRICT #1,JACKSON HOLE MIDDLE SCHOOL,3077334234,...,0,0,0,12962000,286000,84000,0,1,215.53,60464.900478
68890,2013,560583000337,56,5605830,337,2001000,2001001,TETON COUNTY SCHOOL DISTRICT #1,ALTA ELEMENTARY,3073532472,...,0,0,0,12962000,286000,84000,0,1,215.53,60464.900478
68891,2013,560583000339,56,5605830,339,2001000,2001003,TETON COUNTY SCHOOL DISTRICT #1,KELLY ELEMENTARY,3077332955,...,0,0,0,12962000,286000,84000,0,1,215.53,60464.900478
68892,2013,560583000341,56,5605830,341,2001000,2001005,TETON COUNTY SCHOOL DISTRICT #1,WILSON ELEMENTARY,3077333077,...,0,0,0,12962000,286000,84000,0,1,215.53,60464.900478
68893,2013,560583000512,56,5605830,512,2001000,2001056,TETON COUNTY SCHOOL DISTRICT #1,SUMMIT HIGH SCHOOL,3077339116,...,0,0,0,12962000,286000,84000,0,1,215.53,60464.900478
68894,2013,560609000342,56,5606090,342,2307000,2307050,WESTON COUNTY SCHOOL DISTRICT #7,UPTON MIDDLE SCHOOL,3074689331,...,0,0,0,871000,0,0,0,1,28.85,55667.244367
68895,2013,560609000363,56,5606090,363,2307000,2307001,WESTON COUNTY SCHOOL DISTRICT #7,UPTON ELEMENTARY,3074689331,...,0,0,0,871000,0,0,0,1,28.85,55667.244367
68896,2013,560609000401,56,5606090,401,2307000,2307055,WESTON COUNTY SCHOOL DISTRICT #7,UPTON HIGH SCHOOL,3074682361,...,0,0,0,871000,0,0,0,1,28.85,55667.244367
68897,2013,560624000343,56,5606240,343,2201000,2201055,WASHAKIE COUNTY SCHOOL DISTRICT #1,WORLAND HIGH SCHOOL,3073472412,...,0,616000,0,7106000,0,0,0,1,114.49,47130.753778
68898,2013,560624000344,56,5606240,344,2201000,2201050,WASHAKIE COUNTY SCHOOL DISTRICT #1,WORLAND MIDDLE SCHOOL,3073473233,...,0,616000,0,7106000,0,0,0,1,114.49,47130.753778
68899,2013,560624000345,56,5606240,345,2201000,2201001,WASHAKIE COUNTY SCHOOL DISTRICT #1,EAST SIDE ELEMENTARY,3073474662,...,0,616000,0,7106000,0,0,0,1,114.49,47130.753778
68900,2013,560624000346,56,5606240,346,2201000,2201002,WASHAKIE COUNTY SCHOOL DISTRICT #1,SOUTH SIDE ELEMENTARY,3073473306,...,0,616000,0,7106000,0,0,0,1,114.49,47130.753778
68901,2013,560624000347,56,5606240,347,2201000,2201003,WASHAKIE COUNTY SCHOOL DISTRICT #1,WEST SIDE ELEMENTARY,3073474298,...,0,616000,0,7106000,0,0,0,1,114.49,47130.753778